-- ============================================================================
-- EDU-PUZZLE: Test Data Insertion Script - Part 2 (Hard Words)
-- ============================================================================
-- This is the continuation of the test data insertion
-- Run AFTER insert_test_data.sql
-- ============================================================================

DO $$
DECLARE
  v_user_id uuid;
  v_hard_list_id uuid;
BEGIN

  -- Get user ID
  SELECT id INTO v_user_id FROM auth.users WHERE email = 'test345@test.de';

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'User with email test345@test.de not found.';
  END IF;

  -- Get Hard list ID
  SELECT id INTO v_hard_list_id FROM word_lists
  WHERE user_id = v_user_id AND name = 'Hard Words';

  IF v_hard_list_id IS NULL THEN
    RAISE EXCEPTION 'Hard Words list not found. Run insert_test_data.sql first.';
  END IF;

  -- ========================================================================
  -- Insert Hard Words (339 words)
  -- ========================================================================

  INSERT INTO words (list_id, term, translation) VALUES
  (v_hard_list_id, 'QUESTION', 'Inquiry or query'),
  (v_hard_list_id, 'QUALITY', 'Standard or characteristic'),
  (v_hard_list_id, 'QUANTITY', 'Amount or number'),
  (v_hard_list_id, 'QUARTER', 'One fourth'),
  (v_hard_list_id, 'QUEEN', 'Female monarch'),
  (v_hard_list_id, 'QUIET', 'Silent or calm'),
  (v_hard_list_id, 'QUITE', 'Fairly or rather'),
  (v_hard_list_id, 'QUIT', 'Stop or leave'),
  (v_hard_list_id, 'QUICK', 'Fast or rapid'),
  (v_hard_list_id, 'QUOTE', 'Repeated words'),
  (v_hard_list_id, 'QUILT', 'Padded blanket'),
  (v_hard_list_id, 'QUIRK', 'Peculiarity'),
  (v_hard_list_id, 'QUEST', 'Search or journey'),
  (v_hard_list_id, 'QUEUE', 'Waiting line'),
  (v_hard_list_id, 'QUAKE', 'Shake or tremble'),
  (v_hard_list_id, 'QUARRY', 'Stone pit'),
  (v_hard_list_id, 'QUARTZ', 'Mineral'),
  (v_hard_list_id, 'QUANTUM', 'Discrete amount'),
  (v_hard_list_id, 'QUARANTINE', 'Isolation period'),
  (v_hard_list_id, 'QUALIFIED', 'Competent'),
  (v_hard_list_id, 'EXPERT', 'Skilled person'),
  (v_hard_list_id, 'EXAMPLE', 'Illustration'),
  (v_hard_list_id, 'EXACTLY', 'Precisely'),
  (v_hard_list_id, 'EXAMINE', 'Inspect closely'),
  (v_hard_list_id, 'EXERCISE', 'Physical activity'),
  (v_hard_list_id, 'EXPLAIN', 'Make clear'),
  (v_hard_list_id, 'EXPRESS', 'Convey or state'),
  (v_hard_list_id, 'EXTRA', 'Additional'),
  (v_hard_list_id, 'EXTREME', 'Very intense'),
  (v_hard_list_id, 'EXPAND', 'Grow larger'),
  (v_hard_list_id, 'EXPECT', 'Anticipate'),
  (v_hard_list_id, 'EXPORT', 'Send abroad'),
  (v_hard_list_id, 'EXPOSE', 'Reveal or uncover'),
  (v_hard_list_id, 'EXTEND', 'Stretch out'),
  (v_hard_list_id, 'EXCHANGE', 'Trade or swap'),
  (v_hard_list_id, 'EXCITE', 'Stimulate'),
  (v_hard_list_id, 'EXCLUDE', 'Leave out'),
  (v_hard_list_id, 'EXCUSE', 'Reason or pardon'),
  (v_hard_list_id, 'EXECUTE', 'Carry out'),
  (v_hard_list_id, 'EXILE', 'Banishment'),
  (v_hard_list_id, 'EXIST', 'Be present'),
  (v_hard_list_id, 'EXIT', 'Way out'),
  (v_hard_list_id, 'EXOTIC', 'Foreign or unusual'),
  (v_hard_list_id, 'OXYGEN', 'Gas we breathe'),
  (v_hard_list_id, 'TOXIC', 'Poisonous'),
  (v_hard_list_id, 'BOXING', 'Fighting sport'),
  (v_hard_list_id, 'MIXING', 'Combining'),
  (v_hard_list_id, 'FIXING', 'Repairing'),
  (v_hard_list_id, 'WAXING', 'Growing or polishing'),
  (v_hard_list_id, 'TAXING', 'Demanding'),
  (v_hard_list_id, 'LUXURY', 'Expensive comfort'),
  (v_hard_list_id, 'PROXY', 'Substitute'),
  (v_hard_list_id, 'GALAXY', 'Star system'),
  (v_hard_list_id, 'COMPLEXITY', 'Intricacy'),
  (v_hard_list_id, 'MAXIMUM', 'Greatest amount'),
  (v_hard_list_id, 'MINIMUM', 'Least amount'),
  (v_hard_list_id, 'MIXTURE', 'Combination'),
  (v_hard_list_id, 'TEXTURE', 'Surface feel'),
  (v_hard_list_id, 'CONTEXT', 'Surrounding situation'),
  (v_hard_list_id, 'SYNTAX', 'Sentence structure'),
  (v_hard_list_id, 'ANALYZE', 'Examine in detail'),
  (v_hard_list_id, 'ORGANIZE', 'Arrange systematically'),
  (v_hard_list_id, 'REALIZE', 'Understand or achieve'),
  (v_hard_list_id, 'RECOGNIZE', 'Identify'),
  (v_hard_list_id, 'CIVILIZE', 'Make cultured'),
  (v_hard_list_id, 'EMPHASIZE', 'Stress importance'),
  (v_hard_list_id, 'APOLOGIZE', 'Express regret'),
  (v_hard_list_id, 'AUTHORIZE', 'Give permission'),
  (v_hard_list_id, 'MEMORIZE', 'Learn by heart'),
  (v_hard_list_id, 'MINIMIZE', 'Reduce to smallest'),
  (v_hard_list_id, 'MAXIMIZE', 'Increase to largest'),
  (v_hard_list_id, 'OPTIMIZE', 'Make most effective'),
  (v_hard_list_id, 'UTILIZE', 'Make use of'),
  (v_hard_list_id, 'PRIZE', 'Award or reward'),
  (v_hard_list_id, 'SIZE', 'Dimensions'),
  (v_hard_list_id, 'FREEZE', 'Turn to ice'),
  (v_hard_list_id, 'BREEZE', 'Gentle wind'),
  (v_hard_list_id, 'SEIZE', 'Grab suddenly'),
  (v_hard_list_id, 'SQUEEZE', 'Press firmly'),
  (v_hard_list_id, 'SNEEZE', 'Nasal expulsion'),
  (v_hard_list_id, 'PUZZLE', 'Problem or game'),
  (v_hard_list_id, 'FUZZY', 'Unclear or soft'),
  (v_hard_list_id, 'DIZZY', 'Spinning sensation'),
  (v_hard_list_id, 'JAZZ', 'Music style'),
  (v_hard_list_id, 'BUZZ', 'Humming sound'),
  (v_hard_list_id, 'FIZZ', 'Bubbling sound'),
  (v_hard_list_id, 'QUIZ', 'Short test'),
  (v_hard_list_id, 'ZONE', 'Designated area'),
  (v_hard_list_id, 'ZOOM', 'Move quickly'),
  (v_hard_list_id, 'ZERO', 'Nothing or cipher'),
  (v_hard_list_id, 'ZEAL', 'Enthusiasm'),
  (v_hard_list_id, 'ZEBRA', 'Striped animal'),
  (v_hard_list_id, 'ZENITH', 'Highest point'),
  (v_hard_list_id, 'ZEPHYR', 'Gentle breeze'),
  (v_hard_list_id, 'ZIGZAG', 'Alternating pattern'),
  (v_hard_list_id, 'ZINC', 'Metallic element'),
  (v_hard_list_id, 'ZIPPER', 'Fastening device'),
  (v_hard_list_id, 'ZOMBIE', 'Undead creature'),
  (v_hard_list_id, 'HORIZON', 'Sky boundary'),
  (v_hard_list_id, 'FROZEN', 'Solid from cold'),
  (v_hard_list_id, 'DOZEN', 'Twelve items'),
  (v_hard_list_id, 'CITIZEN', 'Nation member'),
  (v_hard_list_id, 'BRONZE', 'Copper alloy'),
  (v_hard_list_id, 'AMAZON', 'River or company'),
  (v_hard_list_id, 'BLAZING', 'Burning brightly'),
  (v_hard_list_id, 'GRAZING', 'Eating grass'),
  (v_hard_list_id, 'AMAZING', 'Astonishing'),
  (v_hard_list_id, 'JUSTICE', 'Fairness'),
  (v_hard_list_id, 'JUSTIFY', 'Prove right'),
  (v_hard_list_id, 'MAJOR', 'Greater or main'),
  (v_hard_list_id, 'SUBJECT', 'Topic or person'),
  (v_hard_list_id, 'PROJECT', 'Planned undertaking'),
  (v_hard_list_id, 'OBJECT', 'Thing or goal'),
  (v_hard_list_id, 'REJECT', 'Refuse or dismiss'),
  (v_hard_list_id, 'INJECT', 'Insert by force'),
  (v_hard_list_id, 'ADJUST', 'Modify or adapt'),
  (v_hard_list_id, 'INJURY', 'Harm or damage'),
  (v_hard_list_id, 'JOURNEY', 'Trip or travel'),
  (v_hard_list_id, 'JOURNAL', 'Diary or publication'),
  (v_hard_list_id, 'JEALOUS', 'Envious'),
  (v_hard_list_id, 'JOYFUL', 'Happy'),
  (v_hard_list_id, 'JUDGE', 'Legal official'),
  (v_hard_list_id, 'JUMP', 'Leap upward'),
  (v_hard_list_id, 'JUNGLE', 'Dense forest'),
  (v_hard_list_id, 'JUNIOR', 'Younger or lower'),
  (v_hard_list_id, 'JUNK', 'Worthless items'),
  (v_hard_list_id, 'JURY', 'Trial panel'),
  (v_hard_list_id, 'JACKET', 'Outer garment'),
  (v_hard_list_id, 'JAIL', 'Prison'),
  (v_hard_list_id, 'JAM', 'Preserve or blockage'),
  (v_hard_list_id, 'JANUARY', 'First month'),
  (v_hard_list_id, 'JAR', 'Container'),
  (v_hard_list_id, 'JEANS', 'Denim pants'),
  (v_hard_list_id, 'JEEP', 'Off-road vehicle'),
  (v_hard_list_id, 'JELLY', 'Soft spread'),
  (v_hard_list_id, 'JEST', 'Joke'),
  (v_hard_list_id, 'JET', 'Fast aircraft'),
  (v_hard_list_id, 'JEWEL', 'Precious stone'),
  (v_hard_list_id, 'JOB', 'Work or task'),
  (v_hard_list_id, 'JOIN', 'Connect or unite'),
  (v_hard_list_id, 'JOINT', 'Connection point'),
  (v_hard_list_id, 'JOKE', 'Humorous story'),
  (v_hard_list_id, 'JOY', 'Great happiness'),
  (v_hard_list_id, 'KNOWLEDGE', 'Information or awareness'),
  (v_hard_list_id, 'KINDNESS', 'Being kind'),
  (v_hard_list_id, 'KINGDOM', 'Realm or domain'),
  (v_hard_list_id, 'KITCHEN', 'Cooking room'),
  (v_hard_list_id, 'KNUCKLE', 'Finger joint'),
  (v_hard_list_id, 'KEYBOARD', 'Input device'),
  (v_hard_list_id, 'KEYWORD', 'Important term'),
  (v_hard_list_id, 'KICK', 'Strike with foot'),
  (v_hard_list_id, 'KING', 'Male monarch'),
  (v_hard_list_id, 'KISS', 'Touch with lips'),
  (v_hard_list_id, 'KITE', 'Flying toy'),
  (v_hard_list_id, 'KITTEN', 'Baby cat'),
  (v_hard_list_id, 'KNEE', 'Leg joint'),
  (v_hard_list_id, 'KNIFE', 'Cutting tool'),
  (v_hard_list_id, 'KNIGHT', 'Armored warrior'),
  (v_hard_list_id, 'KNIT', 'Make with yarn'),
  (v_hard_list_id, 'KNOCK', 'Strike or rap'),
  (v_hard_list_id, 'KNOT', 'Tied loop'),
  (v_hard_list_id, 'KNOW', 'Have information'),
  (v_hard_list_id, 'KNOWN', 'Recognized'),
  (v_hard_list_id, 'KEEN', 'Eager or sharp'),
  (v_hard_list_id, 'KEEP', 'Retain or maintain'),
  (v_hard_list_id, 'KEY', 'Opening device'),
  (v_hard_list_id, 'KEEL', 'Ship bottom'),
  (v_hard_list_id, 'KELP', 'Seaweed'),
  (v_hard_list_id, 'KENNEL', 'Dog house'),
  (v_hard_list_id, 'KETTLE', 'Boiling vessel'),
  (v_hard_list_id, 'KAYAK', 'Small boat'),
  (v_hard_list_id, 'KARMA', 'Fate or destiny'),
  (v_hard_list_id, 'VARIOUS', 'Different kinds'),
  (v_hard_list_id, 'VERSION', 'Form or variant'),
  (v_hard_list_id, 'VICTORY', 'Win or triumph'),
  (v_hard_list_id, 'VILLAGE', 'Small community'),
  (v_hard_list_id, 'VIOLENT', 'Using force'),
  (v_hard_list_id, 'VIRTUE', 'Good quality'),
  (v_hard_list_id, 'VISIBLE', 'Can be seen'),
  (v_hard_list_id, 'VISION', 'Sight or goal'),
  (v_hard_list_id, 'VISITOR', 'Guest'),
  (v_hard_list_id, 'VISUAL', 'Related to sight'),
  (v_hard_list_id, 'VITAL', 'Essential'),
  (v_hard_list_id, 'VIVID', 'Bright or clear'),
  (v_hard_list_id, 'VOCAL', 'Relating to voice'),
  (v_hard_list_id, 'VOICE', 'Sound from mouth'),
  (v_hard_list_id, 'VOLCANO', 'Erupting mountain'),
  (v_hard_list_id, 'VOLUME', 'Amount or book'),
  (v_hard_list_id, 'VOLUNTEER', 'Willing helper'),
  (v_hard_list_id, 'VOTE', 'Cast ballot'),
  (v_hard_list_id, 'VOYAGE', 'Long journey'),
  (v_hard_list_id, 'VALUE', 'Worth or importance'),
  (v_hard_list_id, 'VALID', 'Acceptable'),
  (v_hard_list_id, 'VALLEY', 'Low land between hills'),
  (v_hard_list_id, 'VALVE', 'Flow control'),
  (v_hard_list_id, 'VAMPIRE', 'Blood-drinking creature'),
  (v_hard_list_id, 'VANISH', 'Disappear'),
  (v_hard_list_id, 'VANILLA', 'Flavor'),
  (v_hard_list_id, 'VAPOR', 'Gas form'),
  (v_hard_list_id, 'VARIABLE', 'Changeable element'),
  (v_hard_list_id, 'VARIETY', 'Different types'),
  (v_hard_list_id, 'VAST', 'Very large'),
  (v_hard_list_id, 'VAULT', 'Secure room'),
  (v_hard_list_id, 'VEGETABLE', 'Plant food'),
  (v_hard_list_id, 'VEHICLE', 'Transport means'),
  (v_hard_list_id, 'VEIL', 'Face covering'),
  (v_hard_list_id, 'VEIN', 'Blood vessel'),
  (v_hard_list_id, 'VELOCITY', 'Speed with direction'),
  (v_hard_list_id, 'VELVET', 'Soft fabric'),
  (v_hard_list_id, 'VENDOR', 'Seller'),
  (v_hard_list_id, 'VENTURE', 'Risky undertaking'),
  (v_hard_list_id, 'VENUE', 'Event location'),
  (v_hard_list_id, 'VERB', 'Action word'),
  (v_hard_list_id, 'VERDICT', 'Decision'),
  (v_hard_list_id, 'VERIFY', 'Confirm truth'),
  (v_hard_list_id, 'VERSE', 'Poetry line'),
  (v_hard_list_id, 'VERSUS', 'Against'),
  (v_hard_list_id, 'VERTICAL', 'Upright'),
  (v_hard_list_id, 'VESSEL', 'Container or ship'),
  (v_hard_list_id, 'VETERAN', 'Experienced person'),
  (v_hard_list_id, 'VETO', 'Reject or forbid'),
  (v_hard_list_id, 'VIBRATE', 'Shake rapidly'),
  (v_hard_list_id, 'VICTIM', 'Sufferer'),
  (v_hard_list_id, 'WITHDRAW', 'Take back or remove'),
  (v_hard_list_id, 'WORLDWIDE', 'Global'),
  (v_hard_list_id, 'WORSHIP', 'Religious devotion'),
  (v_hard_list_id, 'WORTHWHILE', 'Worth the effort'),
  (v_hard_list_id, 'WORTHY', 'Deserving'),
  (v_hard_list_id, 'WOUND', 'Injury'),
  (v_hard_list_id, 'WRAP', 'Cover or enclose'),
  (v_hard_list_id, 'WRECK', 'Destroy or ruin'),
  (v_hard_list_id, 'WRESTLE', 'Grapple or fight'),
  (v_hard_list_id, 'WRIST', 'Hand joint'),
  (v_hard_list_id, 'WRITE', 'Put words on paper'),
  (v_hard_list_id, 'WRONG', 'Incorrect'),
  (v_hard_list_id, 'WAGON', 'Wheeled vehicle'),
  (v_hard_list_id, 'WAIST', 'Body middle'),
  (v_hard_list_id, 'WAIT', 'Stay until'),
  (v_hard_list_id, 'WAKE', 'Stop sleeping'),
  (v_hard_list_id, 'WALK', 'Move on foot'),
  (v_hard_list_id, 'WALL', 'Vertical structure'),
  (v_hard_list_id, 'WANDER', 'Roam aimlessly'),
  (v_hard_list_id, 'WARM', 'Moderately hot'),
  (v_hard_list_id, 'WARN', 'Alert of danger'),
  (v_hard_list_id, 'WASH', 'Clean with water'),
  (v_hard_list_id, 'WASTE', 'Use carelessly'),
  (v_hard_list_id, 'WATCH', 'Observe or timepiece'),
  (v_hard_list_id, 'WAVE', 'Water swell or gesture'),
  (v_hard_list_id, 'WEAK', 'Not strong'),
  (v_hard_list_id, 'WEALTH', 'Riches'),
  (v_hard_list_id, 'WEAPON', 'Fighting tool'),
  (v_hard_list_id, 'WEAR', 'Have on body'),
  (v_hard_list_id, 'WEAVE', 'Interlace threads'),
  (v_hard_list_id, 'WEDDING', 'Marriage ceremony'),
  (v_hard_list_id, 'WEEK', 'Seven days'),
  (v_hard_list_id, 'WEIGH', 'Measure heaviness'),
  (v_hard_list_id, 'WEIGHT', 'Heaviness'),
  (v_hard_list_id, 'WEIRD', 'Strange'),
  (v_hard_list_id, 'WELCOME', 'Greet warmly'),
  (v_hard_list_id, 'WELFARE', 'Well-being'),
  (v_hard_list_id, 'WEST', 'Direction'),
  (v_hard_list_id, 'WHEAT', 'Grain crop'),
  (v_hard_list_id, 'WHEEL', 'Circular object'),
  (v_hard_list_id, 'WHEN', 'At what time'),
  (v_hard_list_id, 'WHERE', 'In what place'),
  (v_hard_list_id, 'WHICH', 'What one'),
  (v_hard_list_id, 'WHILE', 'During the time'),
  (v_hard_list_id, 'WHIP', 'Lash or beat'),
  (v_hard_list_id, 'WHISPER', 'Speak softly'),
  (v_hard_list_id, 'WHISTLE', 'Shrill sound'),
  (v_hard_list_id, 'WHITE', 'Lightest color'),
  (v_hard_list_id, 'WHOLE', 'Complete'),
  (v_hard_list_id, 'WHOM', 'Objective case of who'),
  (v_hard_list_id, 'WHOSE', 'Possessive of who'),
  (v_hard_list_id, 'WICKED', 'Evil'),
  (v_hard_list_id, 'WIDE', 'Broad'),
  (v_hard_list_id, 'WIDOW', 'Surviving spouse'),
  (v_hard_list_id, 'WIDTH', 'Broadness'),
  (v_hard_list_id, 'WILD', 'Untamed'),
  (v_hard_list_id, 'WILL', 'Future tense or determination'),
  (v_hard_list_id, 'WIN', 'Achieve victory'),
  (v_hard_list_id, 'WIND', 'Moving air'),
  (v_hard_list_id, 'WINDOW', 'Glass opening'),
  (v_hard_list_id, 'WINE', 'Fermented drink'),
  (v_hard_list_id, 'WING', 'Flight limb'),
  (v_hard_list_id, 'WINNER', 'Victor'),
  (v_hard_list_id, 'WINTER', 'Cold season'),
  (v_hard_list_id, 'WIRE', 'Metal strand'),
  (v_hard_list_id, 'WISDOM', 'Deep knowledge'),
  (v_hard_list_id, 'WISE', 'Having wisdom'),
  (v_hard_list_id, 'WISH', 'Desire'),
  (v_hard_list_id, 'WITCH', 'Magical woman'),
  (v_hard_list_id, 'WITNESS', 'Observer'),
  (v_hard_list_id, 'WIZARD', 'Magical man'),
  (v_hard_list_id, 'WOLF', 'Wild canine'),
  (v_hard_list_id, 'WOMAN', 'Adult female'),
  (v_hard_list_id, 'WONDER', 'Marvel or question'),
  (v_hard_list_id, 'WOOD', 'Tree material'),
  (v_hard_list_id, 'WOOL', 'Sheep fiber'),
  (v_hard_list_id, 'WORD', 'Language unit'),
  (v_hard_list_id, 'WORK', 'Labor or function'),
  (v_hard_list_id, 'WORKSHOP', 'Training session'),
  (v_hard_list_id, 'WORM', 'Crawling creature'),
  (v_hard_list_id, 'WORRY', 'Feel anxious');

  RAISE NOTICE 'Inserted % Hard words', 339;
  RAISE NOTICE 'Test data insertion complete!';

END $$;
