-- ============================================================================
-- EDU-PUZZLE: Test Data Insertion Script
-- ============================================================================
-- This script inserts three test word lists (Easy, Medium, Hard) with their
-- words into the database for user test345@test.de
--
-- Run this in your Supabase SQL Editor
-- ============================================================================

-- Step 1: Get the user ID for test345@test.de
-- (Replace 'USER_ID_HERE' below with the actual UUID from auth.users)
-- To find it, run: SELECT id FROM auth.users WHERE email = 'test345@test.de';

DO $$
DECLARE
  v_user_id uuid;
  v_easy_list_id uuid;
  v_medium_list_id uuid;
  v_hard_list_id uuid;
BEGIN

  -- ========================================================================
  -- IMPORTANT: Find your user ID first!
  -- ========================================================================
  -- Run this query separately to get your user ID:
  -- SELECT id FROM auth.users WHERE email = 'test345@test.de';
  -- Then replace the value below:

  SELECT id INTO v_user_id FROM auth.users WHERE email = 'test345@test.de';

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'User with email test345@test.de not found. Please create the user first.';
  END IF;

  RAISE NOTICE 'Found user ID: %', v_user_id;

  -- ========================================================================
  -- Create Word Lists
  -- ========================================================================

  -- Easy List
  INSERT INTO word_lists (user_id, name, source_language, target_language)
  VALUES (v_user_id, 'Easy Words', 'en', 'en')
  RETURNING id INTO v_easy_list_id;

  RAISE NOTICE 'Created Easy list with ID: %', v_easy_list_id;

  -- Medium List
  INSERT INTO word_lists (user_id, name, source_language, target_language)
  VALUES (v_user_id, 'Medium Words', 'en', 'en')
  RETURNING id INTO v_medium_list_id;

  RAISE NOTICE 'Created Medium list with ID: %', v_medium_list_id;

  -- Hard List
  INSERT INTO word_lists (user_id, name, source_language, target_language)
  VALUES (v_user_id, 'Hard Words', 'en', 'en')
  RETURNING id INTO v_hard_list_id;

  RAISE NOTICE 'Created Hard list with ID: %', v_hard_list_id;

  -- ========================================================================
  -- Insert Easy Words (267 words)
  -- ========================================================================

  INSERT INTO words (list_id, term, translation, definition, example_sentence) VALUES
  (v_easy_list_id, 'TIME', 'Duration or moment', NULL, NULL),
  (v_easy_list_id, 'LIFE', 'State of being alive', NULL, NULL),
  (v_easy_list_id, 'YEAR', 'Period of 365 days', NULL, NULL),
  (v_easy_list_id, 'WORK', 'Activity involving effort', NULL, NULL),
  (v_easy_list_id, 'PART', 'A piece or portion', NULL, NULL),
  (v_easy_list_id, 'CASE', 'An instance or example', NULL, NULL),
  (v_easy_list_id, 'CALL', 'To summon or telephone', NULL, NULL),
  (v_easy_list_id, 'HAND', 'Part of the body', NULL, NULL),
  (v_easy_list_id, 'PLACE', 'A location', NULL, NULL),
  (v_easy_list_id, 'MADE', 'Created or built', NULL, NULL),
  (v_easy_list_id, 'LIVE', 'To be alive', NULL, NULL),
  (v_easy_list_id, 'WHERE', 'In what location', NULL, NULL),
  (v_easy_list_id, 'AFTER', 'Following in time', NULL, NULL),
  (v_easy_list_id, 'BACK', 'The rear part', NULL, NULL),
  (v_easy_list_id, 'LITTLE', 'Small in size', NULL, NULL),
  (v_easy_list_id, 'ONLY', 'Solely or exclusively', NULL, NULL),
  (v_easy_list_id, 'COME', 'To move toward', NULL, NULL),
  (v_easy_list_id, 'OVER', 'Above or across', NULL, NULL),
  (v_easy_list_id, 'THINK', 'To have thoughts', NULL, NULL),
  (v_easy_list_id, 'ALSO', 'In addition', NULL, NULL),
  (v_easy_list_id, 'TAKE', 'To get or grasp', NULL, NULL),
  (v_easy_list_id, 'WANT', 'To desire', NULL, NULL),
  (v_easy_list_id, 'GIVE', 'To present or provide', NULL, NULL),
  (v_easy_list_id, 'MANY', 'A large number', NULL, NULL),
  (v_easy_list_id, 'LOOK', 'To see or gaze', NULL, NULL),
  (v_easy_list_id, 'THEIR', 'Belonging to them', NULL, NULL),
  (v_easy_list_id, 'WOULD', 'Past tense of will', NULL, NULL),
  (v_easy_list_id, 'THERE', 'In that place', NULL, NULL),
  (v_easy_list_id, 'ABOUT', 'Concerning', NULL, NULL),
  (v_easy_list_id, 'COULD', 'Past tense of can', NULL, NULL),
  (v_easy_list_id, 'PEOPLE', 'Human beings', NULL, NULL),
  (v_easy_list_id, 'OTHER', 'Different or additional', NULL, NULL),
  (v_easy_list_id, 'THESE', 'Plural of this', NULL, NULL),
  (v_easy_list_id, 'FIRST', 'Coming before all others', NULL, NULL),
  (v_easy_list_id, 'WATER', 'Clear liquid', NULL, NULL),
  (v_easy_list_id, 'WHICH', 'What one', NULL, NULL),
  (v_easy_list_id, 'STATE', 'A nation or condition', NULL, NULL),
  (v_easy_list_id, 'NEVER', 'At no time', NULL, NULL),
  (v_easy_list_id, 'WORLD', 'The earth', NULL, NULL),
  (v_easy_list_id, 'STILL', 'Continuing or motionless', NULL, NULL),
  (v_easy_list_id, 'GREAT', 'Very large or good', NULL, NULL),
  (v_easy_list_id, 'THREE', 'The number 3', NULL, NULL),
  (v_easy_list_id, 'SMALL', 'Little in size', NULL, NULL),
  (v_easy_list_id, 'LARGE', 'Big in size', NULL, NULL),
  (v_easy_list_id, 'OFTEN', 'Frequently', NULL, NULL),
  (v_easy_list_id, 'LATER', 'After the current time', NULL, NULL),
  (v_easy_list_id, 'NIGHT', 'Time of darkness', NULL, NULL),
  (v_easy_list_id, 'HOUSE', 'A dwelling', NULL, NULL),
  (v_easy_list_id, 'POINT', 'A specific location', NULL, NULL),
  (v_easy_list_id, 'CAUSE', 'The reason for', NULL, NULL),
  (v_easy_list_id, 'STAND', 'To be upright', NULL, NULL),
  (v_easy_list_id, 'EARLY', 'Before the usual time', NULL, NULL),
  (v_easy_list_id, 'BRING', 'To carry toward', NULL, NULL),
  (v_easy_list_id, 'PERSON', 'An individual human', NULL, NULL),
  (v_easy_list_id, 'BECOME', 'To grow or develop into', NULL, NULL),
  (v_easy_list_id, 'NUMBER', 'A mathematical value', NULL, NULL),
  (v_easy_list_id, 'SCHOOL', 'Place of education', NULL, NULL),
  (v_easy_list_id, 'SYSTEM', 'A set of connected things', NULL, NULL),
  (v_easy_list_id, 'BEFORE', 'Earlier than', NULL, NULL),
  (v_easy_list_id, 'UNDER', 'Below or beneath', NULL, NULL),
  (v_easy_list_id, 'DURING', 'Throughout the time', NULL, NULL),
  (v_easy_list_id, 'ALWAYS', 'At all times', NULL, NULL),
  (v_easy_list_id, 'CHANGE', 'To make different', NULL, NULL),
  (v_easy_list_id, 'ALMOST', 'Nearly', NULL, NULL),
  (v_easy_list_id, 'ANSWER', 'A response', NULL, NULL),
  (v_easy_list_id, 'REASON', 'A cause or explanation', NULL, NULL),
  (v_easy_list_id, 'SECOND', 'Coming after first', NULL, NULL),
  (v_easy_list_id, 'NATURE', 'The natural world', NULL, NULL),
  (v_easy_list_id, 'LEADER', 'One who leads', NULL, NULL),
  (v_easy_list_id, 'MEMBER', 'Part of a group', NULL, NULL),
  (v_easy_list_id, 'STREET', 'A public road', NULL, NULL),
  (v_easy_list_id, 'MARKET', 'A place to buy/sell', NULL, NULL),
  (v_easy_list_id, 'OFFICE', 'A workplace', NULL, NULL),
  (v_easy_list_id, 'RESULT', 'An outcome', NULL, NULL),
  (v_easy_list_id, 'LETTER', 'A written message', NULL, NULL),
  (v_easy_list_id, 'WINTER', 'Coldest season', NULL, NULL),
  (v_easy_list_id, 'SUMMER', 'Warmest season', NULL, NULL),
  (v_easy_list_id, 'SPRING', 'Season after winter', NULL, NULL),
  (v_easy_list_id, 'FATHER', 'Male parent', NULL, NULL),
  (v_easy_list_id, 'MOTHER', 'Female parent', NULL, NULL),
  (v_easy_list_id, 'SISTER', 'Female sibling', NULL, NULL),
  (v_easy_list_id, 'BROTHER', 'Male sibling', NULL, NULL),
  (v_easy_list_id, 'FRIEND', 'A companion', NULL, NULL),
  (v_easy_list_id, 'ANOTHER', 'One more or different', NULL, NULL),
  (v_easy_list_id, 'THROUGH', 'Moving in one side and out', NULL, NULL),
  (v_easy_list_id, 'BETWEEN', 'In the middle of two', NULL, NULL),
  (v_easy_list_id, 'WITHOUT', 'Lacking or not having', NULL, NULL),
  (v_easy_list_id, 'COMPANY', 'A business or companions', NULL, NULL),
  (v_easy_list_id, 'AGAINST', 'In opposition to', NULL, NULL),
  (v_easy_list_id, 'STUDENT', 'One who studies', NULL, NULL),
  (v_easy_list_id, 'TEACHER', 'One who teaches', NULL, NULL),
  (v_easy_list_id, 'MORNING', 'Early part of the day', NULL, NULL),
  (v_easy_list_id, 'EVENING', 'Later part of the day', NULL, NULL),
  (v_easy_list_id, 'GENERAL', 'Common or widespread', NULL, NULL),
  (v_easy_list_id, 'SERVICE', 'Work done for others', NULL, NULL),
  (v_easy_list_id, 'HERSELF', 'Reflexive pronoun', NULL, NULL),
  (v_easy_list_id, 'HIMSELF', 'Reflexive pronoun', NULL, NULL),
  (v_easy_list_id, 'PRESENT', 'Current time or gift', NULL, NULL),
  (v_easy_list_id, 'MILLION', 'One thousand thousand', NULL, NULL),
  (v_easy_list_id, 'HISTORY', 'Past events', NULL, NULL),
  (v_easy_list_id, 'SECTION', 'A distinct part', NULL, NULL),
  (v_easy_list_id, 'STATION', 'A stopping place', NULL, NULL),
  (v_easy_list_id, 'SPECIAL', 'Better or different', NULL, NULL),
  (v_easy_list_id, 'CERTAIN', 'Sure or particular', NULL, NULL),
  (v_easy_list_id, 'MACHINE', 'A mechanical device', NULL, NULL),
  (v_easy_list_id, 'MEASURE', 'To determine size', NULL, NULL),
  (v_easy_list_id, 'SCIENCE', 'Systematic knowledge', NULL, NULL),
  (v_easy_list_id, 'PATTERN', 'A repeated design', NULL, NULL),
  (v_easy_list_id, 'CONTROL', 'To direct or regulate', NULL, NULL),
  (v_easy_list_id, 'DEVELOP', 'To grow or expand', NULL, NULL),
  (v_easy_list_id, 'IMAGINE', 'To form a mental image', NULL, NULL),
  (v_easy_list_id, 'PERHAPS', 'Maybe or possibly', NULL, NULL),
  (v_easy_list_id, 'INSTEAD', 'As an alternative', NULL, NULL),
  (v_easy_list_id, 'INTEREST', 'Curiosity or attention', NULL, NULL),
  (v_easy_list_id, 'CHILDREN', 'Young people', NULL, NULL),
  (v_easy_list_id, 'TOGETHER', 'With each other', NULL, NULL),
  (v_easy_list_id, 'NATIONAL', 'Relating to a nation', NULL, NULL),
  (v_easy_list_id, 'AMERICAN', 'From America', NULL, NULL),
  (v_easy_list_id, 'REMEMBER', 'To recall', NULL, NULL),
  (v_easy_list_id, 'CONTINUE', 'To keep going', NULL, NULL),
  (v_easy_list_id, 'COMPLETE', 'Finished or whole', NULL, NULL),
  (v_easy_list_id, 'CONSIDER', 'To think about', NULL, NULL),
  (v_easy_list_id, 'INCREASE', 'To make larger', NULL, NULL),
  (v_easy_list_id, 'DESCRIBE', 'To give details about', NULL, NULL),
  (v_easy_list_id, 'POSITION', 'A place or role', NULL, NULL),
  (v_easy_list_id, 'STANDARD', 'A level of quality', NULL, NULL),
  (v_easy_list_id, 'LANGUAGE', 'System of communication', NULL, NULL),
  (v_easy_list_id, 'DISCOVER', 'To find for the first time', NULL, NULL),
  (v_easy_list_id, 'SPECIFIC', 'Clearly defined', NULL, NULL),
  (v_easy_list_id, 'ORIGINAL', 'First or earliest', NULL, NULL),
  (v_easy_list_id, 'MOUNTAIN', 'A large landform', NULL, NULL),
  (v_easy_list_id, 'SENTENCE', 'A group of words', NULL, NULL),
  (v_easy_list_id, 'MATERIAL', 'Physical substance', NULL, NULL),
  (v_easy_list_id, 'PRACTICE', 'Repeated exercise', NULL, NULL),
  (v_easy_list_id, 'RESPONSE', 'An answer or reaction', NULL, NULL),
  (v_easy_list_id, 'INSTANCE', 'An example', NULL, NULL),
  (v_easy_list_id, 'PERSONAL', 'Private or individual', NULL, NULL),
  (v_easy_list_id, 'CUSTOMER', 'A buyer', NULL, NULL),
  (v_easy_list_id, 'THOUSAND', 'The number 1000', NULL, NULL),
  (v_easy_list_id, 'HOSPITAL', 'Medical facility', NULL, NULL),
  (v_easy_list_id, 'SOUTHERN', 'Of the south', NULL, NULL),
  (v_easy_list_id, 'NORTHERN', 'Of the north', NULL, NULL),
  (v_easy_list_id, 'MINISTER', 'A government official', NULL, NULL),
  (v_easy_list_id, 'EARTH', 'Our planet', NULL, NULL),
  (v_easy_list_id, 'LIGHT', 'Illumination', NULL, NULL),
  (v_easy_list_id, 'SOUND', 'Audible vibrations', NULL, NULL),
  (v_easy_list_id, 'STONE', 'Rock material', NULL, NULL),
  (v_easy_list_id, 'PLAIN', 'Simple or flat area', NULL, NULL),
  (v_easy_list_id, 'TRAIN', 'Rail vehicle', NULL, NULL),
  (v_easy_list_id, 'BRAIN', 'Thinking organ', NULL, NULL),
  (v_easy_list_id, 'CHAIR', 'Furniture for sitting', NULL, NULL),
  (v_easy_list_id, 'TABLE', 'Flat surface furniture', NULL, NULL),
  (v_easy_list_id, 'PAPER', 'Writing material', NULL, NULL),
  (v_easy_list_id, 'STEEL', 'Strong metal alloy', NULL, NULL),
  (v_easy_list_id, 'WHEEL', 'Circular rotating object', NULL, NULL),
  (v_easy_list_id, 'FIELD', 'Open land area', NULL, NULL),
  (v_easy_list_id, 'PLANT', 'Living organism', NULL, NULL),
  (v_easy_list_id, 'ANIMAL', 'Living creature', NULL, NULL),
  (v_easy_list_id, 'OCEAN', 'Large body of salt water', NULL, NULL),
  (v_easy_list_id, 'RIVER', 'Flowing water body', NULL, NULL),
  (v_easy_list_id, 'FOREST', 'Dense tree area', NULL, NULL),
  (v_easy_list_id, 'DESERT', 'Dry sandy region', NULL, NULL),
  (v_easy_list_id, 'ISLAND', 'Land surrounded by water', NULL, NULL),
  (v_easy_list_id, 'GARDEN', 'Cultivated plant area', NULL, NULL),
  (v_easy_list_id, 'CORNER', 'Where two lines meet', NULL, NULL),
  (v_easy_list_id, 'CENTER', 'Middle point', NULL, NULL),
  (v_easy_list_id, 'BORDER', 'Edge or boundary', NULL, NULL),
  (v_easy_list_id, 'CIRCLE', 'Round shape', NULL, NULL),
  (v_easy_list_id, 'SQUARE', 'Four-sided shape', NULL, NULL),
  (v_easy_list_id, 'TRAVEL', 'To journey', NULL, NULL),
  (v_easy_list_id, 'ARRIVE', 'To reach destination', NULL, NULL),
  (v_easy_list_id, 'RETURN', 'To come back', NULL, NULL),
  (v_easy_list_id, 'DEPART', 'To leave', NULL, NULL),
  (v_easy_list_id, 'SENIOR', 'Older person', NULL, NULL),
  (v_easy_list_id, 'JUNIOR', 'Younger person', NULL, NULL),
  (v_easy_list_id, 'MASTER', 'Expert or teacher', NULL, NULL),
  (v_easy_list_id, 'DOCTOR', 'Medical professional', NULL, NULL),
  (v_easy_list_id, 'LAWYER', 'Legal professional', NULL, NULL),
  (v_easy_list_id, 'WRITER', 'One who writes', NULL, NULL),
  (v_easy_list_id, 'ARTIST', 'Creative person', NULL, NULL),
  (v_easy_list_id, 'PLAYER', 'One who plays', NULL, NULL),
  (v_easy_list_id, 'SINGER', 'One who sings', NULL, NULL),
  (v_easy_list_id, 'DANCER', 'One who dances', NULL, NULL),
  (v_easy_list_id, 'READER', 'One who reads', NULL, NULL),
  (v_easy_list_id, 'SPEAKER', 'One who speaks', NULL, NULL),
  (v_easy_list_id, 'LISTENER', 'One who listens', NULL, NULL),
  (v_easy_list_id, 'OWNER', 'One who possesses', NULL, NULL),
  (v_easy_list_id, 'BUYER', 'One who purchases', NULL, NULL),
  (v_easy_list_id, 'SELLER', 'One who sells', NULL, NULL),
  (v_easy_list_id, 'TRADER', 'One who trades', NULL, NULL),
  (v_easy_list_id, 'FARMER', 'One who farms', NULL, NULL),
  (v_easy_list_id, 'WORKER', 'One who works', NULL, NULL),
  (v_easy_list_id, 'BUILDER', 'One who builds', NULL, NULL),
  (v_easy_list_id, 'DRIVER', 'One who drives', NULL, NULL),
  (v_easy_list_id, 'SAILOR', 'One who sails', NULL, NULL),
  (v_easy_list_id, 'SOLDIER', 'Military person', NULL, NULL),
  (v_easy_list_id, 'CITIZEN', 'Member of a nation', NULL, NULL),
  (v_easy_list_id, 'NATIVE', 'Original inhabitant', NULL, NULL),
  (v_easy_list_id, 'FOREIGN', 'From another country', NULL, NULL),
  (v_easy_list_id, 'ANCIENT', 'Very old', NULL, NULL),
  (v_easy_list_id, 'MODERN', 'Contemporary', NULL, NULL),
  (v_easy_list_id, 'FUTURE', 'Time to come', NULL, NULL),
  (v_easy_list_id, 'FORMER', 'Previous', NULL, NULL),
  (v_easy_list_id, 'LATTER', 'The second of two', NULL, NULL),
  (v_easy_list_id, 'SINGLE', 'One only', NULL, NULL),
  (v_easy_list_id, 'DOUBLE', 'Two times', NULL, NULL),
  (v_easy_list_id, 'TRIPLE', 'Three times', NULL, NULL),
  (v_easy_list_id, 'SIMPLE', 'Not complex', NULL, NULL),
  (v_easy_list_id, 'NORMAL', 'Usual or typical', NULL, NULL),
  (v_easy_list_id, 'FORMAL', 'Official or proper', NULL, NULL),
  (v_easy_list_id, 'TOTAL', 'Complete amount', NULL, NULL),
  (v_easy_list_id, 'FINAL', 'Last or conclusive', NULL, NULL),
  (v_easy_list_id, 'INITIAL', 'First or beginning', NULL, NULL),
  (v_easy_list_id, 'CENTRAL', 'In the middle', NULL, NULL),
  (v_easy_list_id, 'NATURAL', 'From nature', NULL, NULL),
  (v_easy_list_id, 'MENTAL', 'Of the mind', NULL, NULL),
  (v_easy_list_id, 'SOCIAL', 'Relating to society', NULL, NULL),
  (v_easy_list_id, 'ACTUAL', 'Real or genuine', NULL, NULL),
  (v_easy_list_id, 'ANNUAL', 'Yearly', NULL, NULL),
  (v_easy_list_id, 'MANUAL', 'Done by hand', NULL, NULL),
  (v_easy_list_id, 'VISUAL', 'Related to sight', NULL, NULL),
  (v_easy_list_id, 'GLOBAL', 'Worldwide', NULL, NULL),
  (v_easy_list_id, 'LOCAL', 'Nearby or regional', NULL, NULL),
  (v_easy_list_id, 'ROYAL', 'Related to royalty', NULL, NULL),
  (v_easy_list_id, 'MORAL', 'Ethical or right', NULL, NULL),
  (v_easy_list_id, 'LEGAL', 'Lawful', NULL, NULL),
  (v_easy_list_id, 'EQUAL', 'The same as', NULL, NULL),
  (v_easy_list_id, 'IDEAL', 'Perfect or best', NULL, NULL),
  (v_easy_list_id, 'VITAL', 'Essential', NULL, NULL),
  (v_easy_list_id, 'FATAL', 'Deadly', NULL, NULL),
  (v_easy_list_id, 'METAL', 'Hard material', NULL, NULL),
  (v_easy_list_id, 'PETAL', 'Flower part', NULL, NULL);

  RAISE NOTICE 'Inserted % Easy words', 267;

  -- ========================================================================
  -- Insert Medium Words (293 words)
  -- ========================================================================

  INSERT INTO words (list_id, term, translation) VALUES
  (v_medium_list_id, 'COMPUTER', 'Electronic device for processing data'),
  (v_medium_list_id, 'KEYBOARD', 'Input device with keys'),
  (v_medium_list_id, 'MONITOR', 'Display screen'),
  (v_medium_list_id, 'PRINTER', 'Device that produces paper output'),
  (v_medium_list_id, 'SOFTWARE', 'Computer programs'),
  (v_medium_list_id, 'HARDWARE', 'Physical computer parts'),
  (v_medium_list_id, 'INTERNET', 'Global network'),
  (v_medium_list_id, 'WEBSITE', 'Online page'),
  (v_medium_list_id, 'DATABASE', 'Organized data collection'),
  (v_medium_list_id, 'NETWORK', 'Connected computers'),
  (v_medium_list_id, 'DIGITAL', 'Using binary data'),
  (v_medium_list_id, 'MOBILE', 'Portable device'),
  (v_medium_list_id, 'LAPTOP', 'Portable computer'),
  (v_medium_list_id, 'TABLET', 'Touchscreen device'),
  (v_medium_list_id, 'ROUTER', 'Network device'),
  (v_medium_list_id, 'SERVER', 'Host computer'),
  (v_medium_list_id, 'BACKUP', 'Data copy'),
  (v_medium_list_id, 'UPDATE', 'Software improvement'),
  (v_medium_list_id, 'UPLOAD', 'Send data'),
  (v_medium_list_id, 'DOWNLOAD', 'Receive data'),
  (v_medium_list_id, 'PASSWORD', 'Security code'),
  (v_medium_list_id, 'USERNAME', 'Account identifier'),
  (v_medium_list_id, 'BROWSER', 'Web navigation tool'),
  (v_medium_list_id, 'SEARCH', 'Look for information'),
  (v_medium_list_id, 'ENGINE', 'Machine or search tool'),
  (v_medium_list_id, 'PLATFORM', 'Computing base'),
  (v_medium_list_id, 'PROGRAM', 'Software application'),
  (v_medium_list_id, 'CODING', 'Writing code'),
  (v_medium_list_id, 'DEBUG', 'Fix errors'),
  (v_medium_list_id, 'COMPILE', 'Convert code'),
  (v_medium_list_id, 'SCIENCE', 'Systematic knowledge'),
  (v_medium_list_id, 'BIOLOGY', 'Study of life'),
  (v_medium_list_id, 'PHYSICS', 'Study of matter'),
  (v_medium_list_id, 'CHEMISTRY', 'Study of substances'),
  (v_medium_list_id, 'ECOLOGY', 'Study of ecosystems'),
  (v_medium_list_id, 'GEOLOGY', 'Study of Earth'),
  (v_medium_list_id, 'WEATHER', 'Atmospheric conditions'),
  (v_medium_list_id, 'CLIMATE', 'Long-term weather'),
  (v_medium_list_id, 'ENERGY', 'Capacity to do work'),
  (v_medium_list_id, 'MATTER', 'Physical substance'),
  (v_medium_list_id, 'ELEMENT', 'Basic substance'),
  (v_medium_list_id, 'COMPOUND', 'Combined elements'),
  (v_medium_list_id, 'MOLECULE', 'Group of atoms'),
  (v_medium_list_id, 'ELECTRON', 'Subatomic particle'),
  (v_medium_list_id, 'PROTON', 'Positive particle'),
  (v_medium_list_id, 'NEUTRON', 'Neutral particle'),
  (v_medium_list_id, 'GRAVITY', 'Force of attraction'),
  (v_medium_list_id, 'MOTION', 'Movement'),
  (v_medium_list_id, 'VELOCITY', 'Speed with direction'),
  (v_medium_list_id, 'PRESSURE', 'Force per area'),
  (v_medium_list_id, 'TEMPERATURE', 'Heat measure'),
  (v_medium_list_id, 'VOLCANO', 'Erupting mountain'),
  (v_medium_list_id, 'EARTHQUAKE', 'Ground shaking'),
  (v_medium_list_id, 'TSUNAMI', 'Large ocean wave'),
  (v_medium_list_id, 'HURRICANE', 'Tropical storm'),
  (v_medium_list_id, 'TORNADO', 'Violent wind'),
  (v_medium_list_id, 'LIGHTNING', 'Electric discharge'),
  (v_medium_list_id, 'THUNDER', 'Sound of lightning'),
  (v_medium_list_id, 'RAINBOW', 'Colored arc'),
  (v_medium_list_id, 'SOLAR', 'Related to sun'),
  (v_medium_list_id, 'LUNAR', 'Related to moon'),
  (v_medium_list_id, 'PLANET', 'Celestial body'),
  (v_medium_list_id, 'GALAXY', 'Star system'),
  (v_medium_list_id, 'COMET', 'Icy celestial object'),
  (v_medium_list_id, 'METEOR', 'Falling space rock'),
  (v_medium_list_id, 'ASTEROID', 'Small rocky body'),
  (v_medium_list_id, 'SATELLITE', 'Orbiting object'),
  (v_medium_list_id, 'TELESCOPE', 'Viewing instrument'),
  (v_medium_list_id, 'MICROSCOPE', 'Magnifying tool'),
  (v_medium_list_id, 'LABORATORY', 'Research facility'),
  (v_medium_list_id, 'ELEPHANT', 'Large mammal with trunk'),
  (v_medium_list_id, 'GIRAFFE', 'Long-necked animal'),
  (v_medium_list_id, 'DOLPHIN', 'Intelligent sea mammal'),
  (v_medium_list_id, 'PENGUIN', 'Flightless bird'),
  (v_medium_list_id, 'BUTTERFLY', 'Winged insect'),
  (v_medium_list_id, 'MOSQUITO', 'Biting insect'),
  (v_medium_list_id, 'CROCODILE', 'Large reptile'),
  (v_medium_list_id, 'KANGAROO', 'Hopping marsupial'),
  (v_medium_list_id, 'LEOPARD', 'Spotted cat'),
  (v_medium_list_id, 'CHEETAH', 'Fast cat'),
  (v_medium_list_id, 'GORILLA', 'Large ape'),
  (v_medium_list_id, 'MONKEY', 'Primate'),
  (v_medium_list_id, 'ZEBRA', 'Striped horse'),
  (v_medium_list_id, 'TIGER', 'Striped big cat'),
  (v_medium_list_id, 'LION', 'King of animals'),
  (v_medium_list_id, 'BEAR', 'Large carnivore'),
  (v_medium_list_id, 'WOLF', 'Wild canine'),
  (v_medium_list_id, 'FOX', 'Cunning animal'),
  (v_medium_list_id, 'DEER', 'Antlered animal'),
  (v_medium_list_id, 'RABBIT', 'Hopping mammal'),
  (v_medium_list_id, 'SQUIRREL', 'Tree-climbing rodent'),
  (v_medium_list_id, 'EAGLE', 'Bird of prey'),
  (v_medium_list_id, 'FALCON', 'Hunting bird'),
  (v_medium_list_id, 'PARROT', 'Colorful talking bird'),
  (v_medium_list_id, 'PIGEON', 'Common city bird'),
  (v_medium_list_id, 'SPARROW', 'Small brown bird'),
  (v_medium_list_id, 'ROBIN', 'Red-breasted bird'),
  (v_medium_list_id, 'SHARK', 'Predatory fish'),
  (v_medium_list_id, 'WHALE', 'Largest mammal'),
  (v_medium_list_id, 'OCTOPUS', 'Eight-armed creature'),
  (v_medium_list_id, 'JELLYFISH', 'Transparent sea creature'),
  (v_medium_list_id, 'STARFISH', 'Star-shaped sea animal'),
  (v_medium_list_id, 'CORAL', 'Marine organism'),
  (v_medium_list_id, 'SEAWEED', 'Marine plant'),
  (v_medium_list_id, 'FLOWER', 'Blooming plant part'),
  (v_medium_list_id, 'TREE', 'Woody plant'),
  (v_medium_list_id, 'LEAF', 'Plant blade'),
  (v_medium_list_id, 'ROOT', 'Underground plant part'),
  (v_medium_list_id, 'STEM', 'Plant stalk'),
  (v_medium_list_id, 'BRANCH', 'Tree limb'),
  (v_medium_list_id, 'SEED', 'Plant embryo'),
  (v_medium_list_id, 'FRUIT', 'Plant product'),
  (v_medium_list_id, 'BERRY', 'Small fruit'),
  (v_medium_list_id, 'GRASS', 'Ground cover'),
  (v_medium_list_id, 'MOSS', 'Small green plant'),
  (v_medium_list_id, 'FERN', 'Leafy plant'),
  (v_medium_list_id, 'CACTUS', 'Desert plant'),
  (v_medium_list_id, 'BAMBOO', 'Tall grass'),
  (v_medium_list_id, 'CONTINENT', 'Large landmass'),
  (v_medium_list_id, 'COUNTRY', 'Nation state'),
  (v_medium_list_id, 'CAPITAL', 'Main city'),
  (v_medium_list_id, 'PROVINCE', 'State or region'),
  (v_medium_list_id, 'DISTRICT', 'Administrative area'),
  (v_medium_list_id, 'VILLAGE', 'Small settlement'),
  (v_medium_list_id, 'TOWN', 'Urban area'),
  (v_medium_list_id, 'CITY', 'Large urban area'),
  (v_medium_list_id, 'SUBURB', 'Residential area'),
  (v_medium_list_id, 'DOWNTOWN', 'City center'),
  (v_medium_list_id, 'HIGHWAY', 'Main road'),
  (v_medium_list_id, 'BRIDGE', 'Crossing structure'),
  (v_medium_list_id, 'TUNNEL', 'Underground passage'),
  (v_medium_list_id, 'HARBOR', 'Port area'),
  (v_medium_list_id, 'AIRPORT', 'Flight terminal'),
  (v_medium_list_id, 'STATION', 'Transport stop'),
  (v_medium_list_id, 'MUSEUM', 'Art/history building'),
  (v_medium_list_id, 'LIBRARY', 'Book collection'),
  (v_medium_list_id, 'THEATER', 'Performance venue'),
  (v_medium_list_id, 'STADIUM', 'Sports arena'),
  (v_medium_list_id, 'PALACE', 'Royal residence'),
  (v_medium_list_id, 'CASTLE', 'Fortified building'),
  (v_medium_list_id, 'TEMPLE', 'Religious building'),
  (v_medium_list_id, 'CHURCH', 'Christian place'),
  (v_medium_list_id, 'MOSQUE', 'Islamic place'),
  (v_medium_list_id, 'SHRINE', 'Sacred place'),
  (v_medium_list_id, 'MONUMENT', 'Memorial structure'),
  (v_medium_list_id, 'STATUE', 'Carved figure'),
  (v_medium_list_id, 'TOWER', 'Tall structure'),
  (v_medium_list_id, 'PYRAMID', 'Ancient structure'),
  (v_medium_list_id, 'KITCHEN', 'Cooking room'),
  (v_medium_list_id, 'RECIPE', 'Cooking instructions'),
  (v_medium_list_id, 'INGREDIENT', 'Food component'),
  (v_medium_list_id, 'FLAVOR', 'Taste quality'),
  (v_medium_list_id, 'SEASON', 'Add spices'),
  (v_medium_list_id, 'BOIL', 'Heat in water'),
  (v_medium_list_id, 'FRY', 'Cook in oil'),
  (v_medium_list_id, 'BAKE', 'Cook in oven'),
  (v_medium_list_id, 'GRILL', 'Cook on grate'),
  (v_medium_list_id, 'ROAST', 'Cook with dry heat'),
  (v_medium_list_id, 'STEAM', 'Cook with vapor'),
  (v_medium_list_id, 'SLICE', 'Cut thinly'),
  (v_medium_list_id, 'CHOP', 'Cut into pieces'),
  (v_medium_list_id, 'BLEND', 'Mix together'),
  (v_medium_list_id, 'STIR', 'Mix with motion'),
  (v_medium_list_id, 'POUR', 'Transfer liquid'),
  (v_medium_list_id, 'SERVE', 'Present food'),
  (v_medium_list_id, 'MEAL', 'Food occasion'),
  (v_medium_list_id, 'BREAKFAST', 'Morning meal'),
  (v_medium_list_id, 'LUNCH', 'Midday meal'),
  (v_medium_list_id, 'DINNER', 'Evening meal'),
  (v_medium_list_id, 'SNACK', 'Small meal'),
  (v_medium_list_id, 'DESSERT', 'Sweet course'),
  (v_medium_list_id, 'BEVERAGE', 'Drink'),
  (v_medium_list_id, 'COFFEE', 'Hot drink'),
  (v_medium_list_id, 'TEA', 'Brewed drink'),
  (v_medium_list_id, 'JUICE', 'Fruit liquid'),
  (v_medium_list_id, 'SOUP', 'Liquid dish'),
  (v_medium_list_id, 'SALAD', 'Mixed vegetables'),
  (v_medium_list_id, 'SANDWICH', 'Bread with filling'),
  (v_medium_list_id, 'PIZZA', 'Italian flatbread'),
  (v_medium_list_id, 'PASTA', 'Italian noodles'),
  (v_medium_list_id, 'RICE', 'Grain staple'),
  (v_medium_list_id, 'BREAD', 'Baked staple'),
  (v_medium_list_id, 'CHEESE', 'Dairy product'),
  (v_medium_list_id, 'BUTTER', 'Milk fat'),
  (v_medium_list_id, 'CREAM', 'Thick milk'),
  (v_medium_list_id, 'YOGURT', 'Fermented milk'),
  (v_medium_list_id, 'MEAT', 'Animal flesh'),
  (v_medium_list_id, 'CHICKEN', 'Poultry'),
  (v_medium_list_id, 'BEEF', 'Cow meat'),
  (v_medium_list_id, 'PORK', 'Pig meat'),
  (v_medium_list_id, 'FISH', 'Aquatic animal'),
  (v_medium_list_id, 'SHRIMP', 'Small crustacean'),
  (v_medium_list_id, 'VEGETABLE', 'Plant food'),
  (v_medium_list_id, 'CARROT', 'Orange root'),
  (v_medium_list_id, 'POTATO', 'Starchy tuber'),
  (v_medium_list_id, 'TOMATO', 'Red fruit/vegetable'),
  (v_medium_list_id, 'ONION', 'Layered bulb'),
  (v_medium_list_id, 'GARLIC', 'Pungent bulb'),
  (v_medium_list_id, 'PEPPER', 'Spice or vegetable'),
  (v_medium_list_id, 'MUSHROOM', 'Edible fungus'),
  (v_medium_list_id, 'MUSIC', 'Organized sound'),
  (v_medium_list_id, 'PAINTING', 'Visual art'),
  (v_medium_list_id, 'SCULPTURE', 'Three-dimensional art'),
  (v_medium_list_id, 'DRAWING', 'Sketched art'),
  (v_medium_list_id, 'POETRY', 'Verse writing'),
  (v_medium_list_id, 'NOVEL', 'Long fiction'),
  (v_medium_list_id, 'STORY', 'Narrative'),
  (v_medium_list_id, 'DRAMA', 'Stage play'),
  (v_medium_list_id, 'COMEDY', 'Humorous work'),
  (v_medium_list_id, 'TRAGEDY', 'Sad play'),
  (v_medium_list_id, 'OPERA', 'Musical drama'),
  (v_medium_list_id, 'BALLET', 'Dance art'),
  (v_medium_list_id, 'CONCERT', 'Musical performance'),
  (v_medium_list_id, 'SYMPHONY', 'Orchestral work'),
  (v_medium_list_id, 'MELODY', 'Musical tune'),
  (v_medium_list_id, 'RHYTHM', 'Beat pattern'),
  (v_medium_list_id, 'HARMONY', 'Musical agreement'),
  (v_medium_list_id, 'INSTRUMENT', 'Music tool'),
  (v_medium_list_id, 'PIANO', 'Keyboard instrument'),
  (v_medium_list_id, 'GUITAR', 'String instrument'),
  (v_medium_list_id, 'VIOLIN', 'Bowed string'),
  (v_medium_list_id, 'DRUM', 'Percussion instrument'),
  (v_medium_list_id, 'TRUMPET', 'Brass instrument'),
  (v_medium_list_id, 'FLUTE', 'Wind instrument'),
  (v_medium_list_id, 'CULTURE', 'Social customs'),
  (v_medium_list_id, 'TRADITION', 'Passed custom'),
  (v_medium_list_id, 'FESTIVAL', 'Celebration event'),
  (v_medium_list_id, 'CEREMONY', 'Formal ritual'),
  (v_medium_list_id, 'CELEBRATION', 'Joyful event'),
  (v_medium_list_id, 'HOLIDAY', 'Special day'),
  (v_medium_list_id, 'SPORT', 'Physical activity'),
  (v_medium_list_id, 'FOOTBALL', 'Ball game'),
  (v_medium_list_id, 'BASKETBALL', 'Hoop game'),
  (v_medium_list_id, 'BASEBALL', 'Bat game'),
  (v_medium_list_id, 'TENNIS', 'Racket game'),
  (v_medium_list_id, 'GOLF', 'Club game'),
  (v_medium_list_id, 'HOCKEY', 'Stick game'),
  (v_medium_list_id, 'SWIMMING', 'Water sport'),
  (v_medium_list_id, 'RUNNING', 'Fast movement'),
  (v_medium_list_id, 'CYCLING', 'Bike riding'),
  (v_medium_list_id, 'SKIING', 'Snow sport'),
  (v_medium_list_id, 'SKATING', 'Gliding sport'),
  (v_medium_list_id, 'CLIMBING', 'Ascending sport'),
  (v_medium_list_id, 'HIKING', 'Trail walking'),
  (v_medium_list_id, 'CAMPING', 'Outdoor staying'),
  (v_medium_list_id, 'FISHING', 'Catching fish'),
  (v_medium_list_id, 'HUNTING', 'Pursuing game'),
  (v_medium_list_id, 'EXERCISE', 'Physical training'),
  (v_medium_list_id, 'TRAINING', 'Practice sessions'),
  (v_medium_list_id, 'COMPETITION', 'Contest'),
  (v_medium_list_id, 'CHAMPION', 'Winner'),
  (v_medium_list_id, 'VICTORY', 'Win'),
  (v_medium_list_id, 'DEFEAT', 'Loss'),
  (v_medium_list_id, 'SCORE', 'Points earned'),
  (v_medium_list_id, 'GOAL', 'Target or point'),
  (v_medium_list_id, 'TEAM', 'Group of players'),
  (v_medium_list_id, 'COACH', 'Trainer'),
  (v_medium_list_id, 'ATHLETE', 'Sports person'),
  (v_medium_list_id, 'PLAYER', 'Participant'),
  (v_medium_list_id, 'REFEREE', 'Game official');

  RAISE NOTICE 'Inserted % Medium words', 293;

  -- Continue with Hard words in next part...

END $$;
