#!/bin/bash
# Quick fix script for Stripe webhook signature error

echo "🔧 Stripe Webhook Secret Fix"
echo "=============================="
echo ""
echo "✅ Good news: 401 error is FIXED!"
echo "❌ Current issue: Signature verification failing (400 error)"
echo ""
echo "This means STRIPE_WEBHOOK_SECRET is not set or incorrect."
echo ""
echo "📋 Steps to fix:"
echo ""
echo "1. Get your webhook signing secret from Stripe:"
echo "   → Go to: https://dashboard.stripe.com/test/webhooks"
echo "   → Click your webhook endpoint"
echo "   → Click 'Reveal' under 'Signing secret'"
echo "   → Copy the secret (starts with whsec_)"
echo ""
echo "2. Set it in Supabase:"
echo "   → Run: supabase secrets set STRIPE_WEBHOOK_SECRET=whsec_your_secret"
echo ""
echo "3. Re-deploy the function:"
echo "   → Run: supabase functions deploy stripe-webhook"
echo ""
echo "4. Test again:"
echo "   → Run: stripe trigger checkout.session.completed"
echo ""
echo "Expected result: 200 OK (not 400)"
echo ""
echo "Need help? See STRIPE_WEBHOOK_SECRET_FIX.md"
