/**
 * @fileoverview Easy difficulty word bank for testing
 *
 * This dataset contains ~250 words with high crossing potential.
 * Characteristics:
 * - Common letters: E, A, R, T, I, O, N, S, L
 * - Good length distribution (4-8 letters mostly)
 * - High letter overlap between words
 *
 * @module lib/test-utils/wordBanks/easy
 */

import type { TestWord } from '../types'

/**
 * Easy difficulty word bank
 * Optimized for high crossing potential in puzzles
 */
export const EASY_WORDS: TestWord[] = [
  // 3-4 letter words
  { term: 'TIME', translation: 'Duration or moment' },
  { term: 'LIFE', translation: 'State of being alive' },
  { term: 'YEAR', translation: 'Period of 365 days' },
  { term: 'WORK', translation: 'Activity involving effort' },
  { term: 'PART', translation: 'A piece or portion' },
  { term: 'CASE', translation: 'An instance or example' },
  { term: 'CALL', translation: 'To summon or telephone' },
  { term: 'HAND', translation: 'Part of the body' },
  { term: 'PLACE', translation: 'A location' },
  { term: 'MADE', translation: 'Created or built' },
  { term: 'LIVE', translation: 'To be alive' },
  { term: 'WHERE', translation: 'In what location' },
  { term: 'AFTER', translation: 'Following in time' },
  { term: 'BACK', translation: 'The rear part' },
  { term: 'LITTLE', translation: 'Small in size' },
  { term: 'ONLY', translation: 'Solely or exclusively' },
  { term: 'COME', translation: 'To move toward' },
  { term: 'OVER', translation: 'Above or across' },
  { term: 'THINK', translation: 'To have thoughts' },
  { term: 'ALSO', translation: 'In addition' },
  { term: 'TAKE', translation: 'To get or grasp' },
  { term: 'WANT', translation: 'To desire' },
  { term: 'GIVE', translation: 'To present or provide' },
  { term: 'MANY', translation: 'A large number' },
  { term: 'LOOK', translation: 'To see or gaze' },

  // 5 letter words
  { term: 'THEIR', translation: 'Belonging to them' },
  { term: 'WOULD', translation: 'Past tense of will' },
  { term: 'THERE', translation: 'In that place' },
  { term: 'ABOUT', translation: 'Concerning' },
  { term: 'COULD', translation: 'Past tense of can' },
  { term: 'PEOPLE', translation: 'Human beings' },
  { term: 'OTHER', translation: 'Different or additional' },
  { term: 'THESE', translation: 'Plural of this' },
  { term: 'FIRST', translation: 'Coming before all others' },
  { term: 'WATER', translation: 'Clear liquid' },
  { term: 'WHICH', translation: 'What one' },
  { term: 'THEIR', translation: 'Possessive pronoun' },
  { term: 'STATE', translation: 'A nation or condition' },
  { term: 'NEVER', translation: 'At no time' },
  { term: 'WORLD', translation: 'The earth' },
  { term: 'STILL', translation: 'Continuing or motionless' },
  { term: 'GREAT', translation: 'Very large or good' },
  { term: 'THREE', translation: 'The number 3' },
  { term: 'SMALL', translation: 'Little in size' },
  { term: 'LARGE', translation: 'Big in size' },
  { term: 'OFTEN', translation: 'Frequently' },
  { term: 'LATER', translation: 'After the current time' },
  { term: 'NIGHT', translation: 'Time of darkness' },
  { term: 'HOUSE', translation: 'A dwelling' },
  { term: 'POINT', translation: 'A specific location' },
  { term: 'CAUSE', translation: 'The reason for' },
  { term: 'STAND', translation: 'To be upright' },
  { term: 'EARLY', translation: 'Before the usual time' },
  { term: 'PLACE', translation: 'A particular position' },
  { term: 'BRING', translation: 'To carry toward' },

  // 6 letter words
  { term: 'PERSON', translation: 'An individual human' },
  { term: 'BECOME', translation: 'To grow or develop into' },
  { term: 'NUMBER', translation: 'A mathematical value' },
  { term: 'SCHOOL', translation: 'Place of education' },
  { term: 'SYSTEM', translation: 'A set of connected things' },
  { term: 'BEFORE', translation: 'Earlier than' },
  { term: 'UNDER', translation: 'Below or beneath' },
  { term: 'DURING', translation: 'Throughout the time' },
  { term: 'ALWAYS', translation: 'At all times' },
  { term: 'CHANGE', translation: 'To make different' },
  { term: 'ALMOST', translation: 'Nearly' },
  { term: 'ANSWER', translation: 'A response' },
  { term: 'REASON', translation: 'A cause or explanation' },
  { term: 'SECOND', translation: 'Coming after first' },
  { term: 'NATURE', translation: 'The natural world' },
  { term: 'LEADER', translation: 'One who leads' },
  { term: 'MEMBER', translation: 'Part of a group' },
  { term: 'STREET', translation: 'A public road' },
  { term: 'MARKET', translation: 'A place to buy/sell' },
  { term: 'OFFICE', translation: 'A workplace' },
  { term: 'RESULT', translation: 'An outcome' },
  { term: 'LETTER', translation: 'A written message' },
  { term: 'WINTER', translation: 'Coldest season' },
  { term: 'SUMMER', translation: 'Warmest season' },
  { term: 'SPRING', translation: 'Season after winter' },
  { term: 'FATHER', translation: 'Male parent' },
  { term: 'MOTHER', translation: 'Female parent' },
  { term: 'SISTER', translation: 'Female sibling' },
  { term: 'BROTHER', translation: 'Male sibling' },
  { term: 'FRIEND', translation: 'A companion' },

  // 7 letter words
  { term: 'ANOTHER', translation: 'One more or different' },
  { term: 'THROUGH', translation: 'Moving in one side and out' },
  { term: 'BETWEEN', translation: 'In the middle of two' },
  { term: 'WITHOUT', translation: 'Lacking or not having' },
  { term: 'COMPANY', translation: 'A business or companions' },
  { term: 'AGAINST', translation: 'In opposition to' },
  { term: 'STUDENT', translation: 'One who studies' },
  { term: 'TEACHER', translation: 'One who teaches' },
  { term: 'MORNING', translation: 'Early part of the day' },
  { term: 'EVENING', translation: 'Later part of the day' },
  { term: 'GENERAL', translation: 'Common or widespread' },
  { term: 'SERVICE', translation: 'Work done for others' },
  { term: 'HERSELF', translation: 'Reflexive pronoun' },
  { term: 'HIMSELF', translation: 'Reflexive pronoun' },
  { term: 'PRESENT', translation: 'Current time or gift' },
  { term: 'MILLION', translation: 'One thousand thousand' },
  { term: 'HISTORY', translation: 'Past events' },
  { term: 'SECTION', translation: 'A distinct part' },
  { term: 'STATION', translation: 'A stopping place' },
  { term: 'SPECIAL', translation: 'Better or different' },
  { term: 'CERTAIN', translation: 'Sure or particular' },
  { term: 'MACHINE', translation: 'A mechanical device' },
  { term: 'MEASURE', translation: 'To determine size' },
  { term: 'SCIENCE', translation: 'Systematic knowledge' },
  { term: 'PATTERN', translation: 'A repeated design' },
  { term: 'CONTROL', translation: 'To direct or regulate' },
  { term: 'DEVELOP', translation: 'To grow or expand' },
  { term: 'IMAGINE', translation: 'To form a mental image' },
  { term: 'PERHAPS', translation: 'Maybe or possibly' },
  { term: 'INSTEAD', translation: 'As an alternative' },

  // 8 letter words
  { term: 'INTEREST', translation: 'Curiosity or attention' },
  { term: 'CHILDREN', translation: 'Young people' },
  { term: 'TOGETHER', translation: 'With each other' },
  { term: 'NATIONAL', translation: 'Relating to a nation' },
  { term: 'AMERICAN', translation: 'From America' },
  { term: 'REMEMBER', translation: 'To recall' },
  { term: 'CONTINUE', translation: 'To keep going' },
  { term: 'COMPLETE', translation: 'Finished or whole' },
  { term: 'CONSIDER', translation: 'To think about' },
  { term: 'INCREASE', translation: 'To make larger' },
  { term: 'DESCRIBE', translation: 'To give details about' },
  { term: 'POSITION', translation: 'A place or role' },
  { term: 'STANDARD', translation: 'A level of quality' },
  { term: 'LANGUAGE', translation: 'System of communication' },
  { term: 'DISCOVER', translation: 'To find for the first time' },
  { term: 'SPECIFIC', translation: 'Clearly defined' },
  { term: 'ORIGINAL', translation: 'First or earliest' },
  { term: 'MOUNTAIN', translation: 'A large landform' },
  { term: 'SENTENCE', translation: 'A group of words' },
  { term: 'MATERIAL', translation: 'Physical substance' },
  { term: 'PRACTICE', translation: 'Repeated exercise' },
  { term: 'RESPONSE', translation: 'An answer or reaction' },
  { term: 'INSTANCE', translation: 'An example' },
  { term: 'PERSONAL', translation: 'Private or individual' },
  { term: 'CUSTOMER', translation: 'A buyer' },
  { term: 'THOUSAND', translation: 'The number 1000' },
  { term: 'HOSPITAL', translation: 'Medical facility' },
  { term: 'SOUTHERN', translation: 'Of the south' },
  { term: 'NORTHERN', translation: 'Of the north' },
  { term: 'MINISTER', translation: 'A government official' },

  // Additional common words for variety
  { term: 'WATER', translation: 'H2O liquid' },
  { term: 'EARTH', translation: 'Our planet' },
  { term: 'LIGHT', translation: 'Illumination' },
  { term: 'SOUND', translation: 'Audible vibrations' },
  { term: 'STONE', translation: 'Rock material' },
  { term: 'PLAIN', translation: 'Simple or flat area' },
  { term: 'TRAIN', translation: 'Rail vehicle' },
  { term: 'BRAIN', translation: 'Thinking organ' },
  { term: 'CHAIR', translation: 'Furniture for sitting' },
  { term: 'TABLE', translation: 'Flat surface furniture' },
  { term: 'PAPER', translation: 'Writing material' },
  { term: 'STEEL', translation: 'Strong metal alloy' },
  { term: 'WHEEL', translation: 'Circular rotating object' },
  { term: 'FIELD', translation: 'Open land area' },
  { term: 'PLANT', translation: 'Living organism' },
  { term: 'ANIMAL', translation: 'Living creature' },
  { term: 'OCEAN', translation: 'Large body of salt water' },
  { term: 'RIVER', translation: 'Flowing water body' },
  { term: 'FOREST', translation: 'Dense tree area' },
  { term: 'DESERT', translation: 'Dry sandy region' },
  { term: 'ISLAND', translation: 'Land surrounded by water' },
  { term: 'GARDEN', translation: 'Cultivated plant area' },
  { term: 'CORNER', translation: 'Where two lines meet' },
  { term: 'CENTER', translation: 'Middle point' },
  { term: 'BORDER', translation: 'Edge or boundary' },
  { term: 'CIRCLE', translation: 'Round shape' },
  { term: 'SQUARE', translation: 'Four-sided shape' },
  { term: 'TRAVEL', translation: 'To journey' },
  { term: 'ARRIVE', translation: 'To reach destination' },
  { term: 'RETURN', translation: 'To come back' },
  { term: 'DEPART', translation: 'To leave' },
  { term: 'SENIOR', translation: 'Older person' },
  { term: 'JUNIOR', translation: 'Younger person' },
  { term: 'MASTER', translation: 'Expert or teacher' },
  { term: 'DOCTOR', translation: 'Medical professional' },
  { term: 'LAWYER', translation: 'Legal professional' },
  { term: 'WRITER', translation: 'One who writes' },
  { term: 'ARTIST', translation: 'Creative person' },
  { term: 'PLAYER', translation: 'One who plays' },
  { term: 'SINGER', translation: 'One who sings' },
  { term: 'DANCER', translation: 'One who dances' },
  { term: 'READER', translation: 'One who reads' },
  { term: 'SPEAKER', translation: 'One who speaks' },
  { term: 'LISTENER', translation: 'One who listens' },
  { term: 'OWNER', translation: 'One who possesses' },
  { term: 'BUYER', translation: 'One who purchases' },
  { term: 'SELLER', translation: 'One who sells' },
  { term: 'TRADER', translation: 'One who trades' },
  { term: 'FARMER', translation: 'One who farms' },
  { term: 'WORKER', translation: 'One who works' },
  { term: 'BUILDER', translation: 'One who builds' },
  { term: 'DRIVER', translation: 'One who drives' },
  { term: 'SAILOR', translation: 'One who sails' },
  { term: 'SOLDIER', translation: 'Military person' },
  { term: 'CITIZEN', translation: 'Member of a nation' },
  { term: 'NATIVE', translation: 'Original inhabitant' },
  { term: 'FOREIGN', translation: 'From another country' },
  { term: 'ANCIENT', translation: 'Very old' },
  { term: 'MODERN', translation: 'Contemporary' },
  { term: 'FUTURE', translation: 'Time to come' },
  { term: 'PRESENT', translation: 'Current time' },
  { term: 'FORMER', translation: 'Previous' },
  { term: 'LATTER', translation: 'The second of two' },
  { term: 'SINGLE', translation: 'One only' },
  { term: 'DOUBLE', translation: 'Two times' },
  { term: 'TRIPLE', translation: 'Three times' },
  { term: 'SIMPLE', translation: 'Not complex' },
  { term: 'NORMAL', translation: 'Usual or typical' },
  { term: 'FORMAL', translation: 'Official or proper' },
  { term: 'TOTAL', translation: 'Complete amount' },
  { term: 'FINAL', translation: 'Last or conclusive' },
  { term: 'INITIAL', translation: 'First or beginning' },
  { term: 'CENTRAL', translation: 'In the middle' },
  { term: 'NATURAL', translation: 'From nature' },
  { term: 'MENTAL', translation: 'Of the mind' },
  { term: 'SOCIAL', translation: 'Relating to society' },
  { term: 'ACTUAL', translation: 'Real or genuine' },
  { term: 'ANNUAL', translation: 'Yearly' },
  { term: 'MANUAL', translation: 'Done by hand' },
  { term: 'VISUAL', translation: 'Related to sight' },
  { term: 'GLOBAL', translation: 'Worldwide' },
  { term: 'LOCAL', translation: 'Nearby or regional' },
  { term: 'ROYAL', translation: 'Related to royalty' },
  { term: 'MORAL', translation: 'Ethical or right' },
  { term: 'LEGAL', translation: 'Lawful' },
  { term: 'EQUAL', translation: 'The same as' },
  { term: 'IDEAL', translation: 'Perfect or best' },
  { term: 'VITAL', translation: 'Essential' },
  { term: 'FATAL', translation: 'Deadly' },
  { term: 'METAL', translation: 'Hard material' },
  { term: 'PETAL', translation: 'Flower part' },
]
