/**
 * @fileoverview Hard difficulty word bank for testing
 *
 * This dataset contains ~250 words with challenging crossing patterns.
 * Characteristics:
 * - Rare letters: Q, X, Z, J, K, V, W
 * - Less common letter combinations
 * - Longer words (6-12 letters)
 * - Lower crossing potential
 *
 * @module lib/test-utils/wordBanks/hard
 */

import type { TestWord } from '../types'

/**
 * Hard difficulty word bank
 * Challenging words for stress-testing the algorithm
 */
export const HARD_WORDS: TestWord[] = [
  // Words with Q
  { term: 'QUESTION', translation: 'Inquiry or query' },
  { term: 'QUALITY', translation: 'Standard or characteristic' },
  { term: 'QUANTITY', translation: 'Amount or number' },
  { term: 'QUARTER', translation: 'One fourth' },
  { term: 'QUEEN', translation: 'Female monarch' },
  { term: 'QUIET', translation: 'Silent or calm' },
  { term: 'QUITE', translation: 'Fairly or rather' },
  { term: 'QUIT', translation: 'Stop or leave' },
  { term: 'QUICK', translation: 'Fast or rapid' },
  { term: 'QUOTE', translation: 'Repeated words' },
  { term: 'QUILT', translation: 'Padded blanket' },
  { term: 'QUIRK', translation: 'Peculiarity' },
  { term: 'QUEST', translation: 'Search or journey' },
  { term: 'QUEUE', translation: 'Waiting line' },
  { term: 'QUAKE', translation: 'Shake or tremble' },
  { term: 'QUARRY', translation: 'Stone pit' },
  { term: 'QUARTZ', translation: 'Mineral' },
  { term: 'QUANTUM', translation: 'Discrete amount' },
  { term: 'QUARANTINE', translation: 'Isolation period' },
  { term: 'QUALIFIED', translation: 'Competent' },

  // Words with X
  { term: 'EXPERT', translation: 'Skilled person' },
  { term: 'EXAMPLE', translation: 'Illustration' },
  { term: 'EXACTLY', translation: 'Precisely' },
  { term: 'EXAMINE', translation: 'Inspect closely' },
  { term: 'EXERCISE', translation: 'Physical activity' },
  { term: 'EXPLAIN', translation: 'Make clear' },
  { term: 'EXPRESS', translation: 'Convey or state' },
  { term: 'EXTRA', translation: 'Additional' },
  { term: 'EXTREME', translation: 'Very intense' },
  { term: 'EXPAND', translation: 'Grow larger' },
  { term: 'EXPECT', translation: 'Anticipate' },
  { term: 'EXPORT', translation: 'Send abroad' },
  { term: 'EXPOSE', translation: 'Reveal or uncover' },
  { term: 'EXTEND', translation: 'Stretch out' },
  { term: 'EXCHANGE', translation: 'Trade or swap' },
  { term: 'EXCITE', translation: 'Stimulate' },
  { term: 'EXCLUDE', translation: 'Leave out' },
  { term: 'EXCUSE', translation: 'Reason or pardon' },
  { term: 'EXECUTE', translation: 'Carry out' },
  { term: 'EXILE', translation: 'Banishment' },
  { term: 'EXIST', translation: 'Be present' },
  { term: 'EXIT', translation: 'Way out' },
  { term: 'EXOTIC', translation: 'Foreign or unusual' },
  { term: 'OXYGEN', translation: 'Gas we breathe' },
  { term: 'TOXIC', translation: 'Poisonous' },
  { term: 'BOXING', translation: 'Fighting sport' },
  { term: 'MIXING', translation: 'Combining' },
  { term: 'FIXING', translation: 'Repairing' },
  { term: 'WAXING', translation: 'Growing or polishing' },
  { term: 'TAXING', translation: 'Demanding' },
  { term: 'LUXURY', translation: 'Expensive comfort' },
  { term: 'PROXY', translation: 'Substitute' },
  { term: 'GALAXY', translation: 'Star system' },
  { term: 'COMPLEXITY', translation: 'Intricacy' },
  { term: 'MAXIMUM', translation: 'Greatest amount' },
  { term: 'MINIMUM', translation: 'Least amount' },
  { term: 'MIXTURE', translation: 'Combination' },
  { term: 'TEXTURE', translation: 'Surface feel' },
  { term: 'CONTEXT', translation: 'Surrounding situation' },
  { term: 'SYNTAX', translation: 'Sentence structure' },

  // Words with Z
  { term: 'ANALYZE', translation: 'Examine in detail' },
  { term: 'ORGANIZE', translation: 'Arrange systematically' },
  { term: 'REALIZE', translation: 'Understand or achieve' },
  { term: 'RECOGNIZE', translation: 'Identify' },
  { term: 'CIVILIZE', translation: 'Make cultured' },
  { term: 'EMPHASIZE', translation: 'Stress importance' },
  { term: 'APOLOGIZE', translation: 'Express regret' },
  { term: 'AUTHORIZE', translation: 'Give permission' },
  { term: 'MEMORIZE', translation: 'Learn by heart' },
  { term: 'MINIMIZE', translation: 'Reduce to smallest' },
  { term: 'MAXIMIZE', translation: 'Increase to largest' },
  { term: 'OPTIMIZE', translation: 'Make most effective' },
  { term: 'UTILIZE', translation: 'Make use of' },
  { term: 'PRIZE', translation: 'Award or reward' },
  { term: 'SIZE', translation: 'Dimensions' },
  { term: 'FREEZE', translation: 'Turn to ice' },
  { term: 'BREEZE', translation: 'Gentle wind' },
  { term: 'SEIZE', translation: 'Grab suddenly' },
  { term: 'SQUEEZE', translation: 'Press firmly' },
  { term: 'SNEEZE', translation: 'Nasal expulsion' },
  { term: 'PUZZLE', translation: 'Problem or game' },
  { term: 'FUZZY', translation: 'Unclear or soft' },
  { term: 'DIZZY', translation: 'Spinning sensation' },
  { term: 'JAZZ', translation: 'Music style' },
  { term: 'BUZZ', translation: 'Humming sound' },
  { term: 'FIZZ', translation: 'Bubbling sound' },
  { term: 'QUIZ', translation: 'Short test' },
  { term: 'ZONE', translation: 'Designated area' },
  { term: 'ZOOM', translation: 'Move quickly' },
  { term: 'ZERO', translation: 'Nothing or cipher' },
  { term: 'ZEAL', translation: 'Enthusiasm' },
  { term: 'ZEBRA', translation: 'Striped animal' },
  { term: 'ZENITH', translation: 'Highest point' },
  { term: 'ZEPHYR', translation: 'Gentle breeze' },
  { term: 'ZIGZAG', translation: 'Alternating pattern' },
  { term: 'ZINC', translation: 'Metallic element' },
  { term: 'ZIPPER', translation: 'Fastening device' },
  { term: 'ZOMBIE', translation: 'Undead creature' },
  { term: 'HORIZON', translation: 'Sky boundary' },
  { term: 'FROZEN', translation: 'Solid from cold' },
  { term: 'DOZEN', translation: 'Twelve items' },
  { term: 'CITIZEN', translation: 'Nation member' },
  { term: 'BRONZE', translation: 'Copper alloy' },
  { term: 'AMAZON', translation: 'River or company' },
  { term: 'BLAZING', translation: 'Burning brightly' },
  { term: 'GRAZING', translation: 'Eating grass' },
  { term: 'AMAZING', translation: 'Astonishing' },

  // Words with J
  { term: 'JUSTICE', translation: 'Fairness' },
  { term: 'JUSTIFY', translation: 'Prove right' },
  { term: 'MAJOR', translation: 'Greater or main' },
  { term: 'SUBJECT', translation: 'Topic or person' },
  { term: 'PROJECT', translation: 'Planned undertaking' },
  { term: 'OBJECT', translation: 'Thing or goal' },
  { term: 'REJECT', translation: 'Refuse or dismiss' },
  { term: 'INJECT', translation: 'Insert by force' },
  { term: 'ADJUST', translation: 'Modify or adapt' },
  { term: 'INJURY', translation: 'Harm or damage' },
  { term: 'JOURNEY', translation: 'Trip or travel' },
  { term: 'JOURNAL', translation: 'Diary or publication' },
  { term: 'JEALOUS', translation: 'Envious' },
  { term: 'JOYFUL', translation: 'Happy' },
  { term: 'JUDGE', translation: 'Legal official' },
  { term: 'JUMP', translation: 'Leap upward' },
  { term: 'JUNGLE', translation: 'Dense forest' },
  { term: 'JUNIOR', translation: 'Younger or lower' },
  { term: 'JUNK', translation: 'Worthless items' },
  { term: 'JURY', translation: 'Trial panel' },
  { term: 'JACKET', translation: 'Outer garment' },
  { term: 'JAIL', translation: 'Prison' },
  { term: 'JAM', translation: 'Preserve or blockage' },
  { term: 'JANUARY', translation: 'First month' },
  { term: 'JAR', translation: 'Container' },
  { term: 'JAZZ', translation: 'Music genre' },
  { term: 'JEANS', translation: 'Denim pants' },
  { term: 'JEEP', translation: 'Off-road vehicle' },
  { term: 'JELLY', translation: 'Soft spread' },
  { term: 'JEST', translation: 'Joke' },
  { term: 'JET', translation: 'Fast aircraft' },
  { term: 'JEWEL', translation: 'Precious stone' },
  { term: 'JOB', translation: 'Work or task' },
  { term: 'JOIN', translation: 'Connect or unite' },
  { term: 'JOINT', translation: 'Connection point' },
  { term: 'JOKE', translation: 'Humorous story' },
  { term: 'JOY', translation: 'Great happiness' },

  // Words with K
  { term: 'KNOWLEDGE', translation: 'Information or awareness' },
  { term: 'KINDNESS', translation: 'Being kind' },
  { term: 'KINGDOM', translation: 'Realm or domain' },
  { term: 'KITCHEN', translation: 'Cooking room' },
  { term: 'KNUCKLE', translation: 'Finger joint' },
  { term: 'KEYBOARD', translation: 'Input device' },
  { term: 'KEYWORD', translation: 'Important term' },
  { term: 'KICK', translation: 'Strike with foot' },
  { term: 'KING', translation: 'Male monarch' },
  { term: 'KISS', translation: 'Touch with lips' },
  { term: 'KITE', translation: 'Flying toy' },
  { term: 'KITTEN', translation: 'Baby cat' },
  { term: 'KNEE', translation: 'Leg joint' },
  { term: 'KNIFE', translation: 'Cutting tool' },
  { term: 'KNIGHT', translation: 'Armored warrior' },
  { term: 'KNIT', translation: 'Make with yarn' },
  { term: 'KNOCK', translation: 'Strike or rap' },
  { term: 'KNOT', translation: 'Tied loop' },
  { term: 'KNOW', translation: 'Have information' },
  { term: 'KNOWN', translation: 'Recognized' },
  { term: 'KEEN', translation: 'Eager or sharp' },
  { term: 'KEEP', translation: 'Retain or maintain' },
  { term: 'KEY', translation: 'Opening device' },
  { term: 'KEEL', translation: 'Ship bottom' },
  { term: 'KELP', translation: 'Seaweed' },
  { term: 'KENNEL', translation: 'Dog house' },
  { term: 'KETTLE', translation: 'Boiling vessel' },
  { term: 'KAYAK', translation: 'Small boat' },
  { term: 'KARMA', translation: 'Fate or destiny' },

  // Words with V
  { term: 'VARIOUS', translation: 'Different kinds' },
  { term: 'VERSION', translation: 'Form or variant' },
  { term: 'VICTORY', translation: 'Win or triumph' },
  { term: 'VILLAGE', translation: 'Small community' },
  { term: 'VIOLENT', translation: 'Using force' },
  { term: 'VIRTUE', translation: 'Good quality' },
  { term: 'VISIBLE', translation: 'Can be seen' },
  { term: 'VISION', translation: 'Sight or goal' },
  { term: 'VISITOR', translation: 'Guest' },
  { term: 'VISUAL', translation: 'Related to sight' },
  { term: 'VITAL', translation: 'Essential' },
  { term: 'VIVID', translation: 'Bright or clear' },
  { term: 'VOCAL', translation: 'Relating to voice' },
  { term: 'VOICE', translation: 'Sound from mouth' },
  { term: 'VOLCANO', translation: 'Erupting mountain' },
  { term: 'VOLUME', translation: 'Amount or book' },
  { term: 'VOLUNTEER', translation: 'Willing helper' },
  { term: 'VOTE', translation: 'Cast ballot' },
  { term: 'VOYAGE', translation: 'Long journey' },
  { term: 'VALUE', translation: 'Worth or importance' },
  { term: 'VALID', translation: 'Acceptable' },
  { term: 'VALLEY', translation: 'Low land between hills' },
  { term: 'VALVE', translation: 'Flow control' },
  { term: 'VAMPIRE', translation: 'Blood-drinking creature' },
  { term: 'VANISH', translation: 'Disappear' },
  { term: 'VANILLA', translation: 'Flavor' },
  { term: 'VAPOR', translation: 'Gas form' },
  { term: 'VARIABLE', translation: 'Changeable element' },
  { term: 'VARIETY', translation: 'Different types' },
  { term: 'VAST', translation: 'Very large' },
  { term: 'VAULT', translation: 'Secure room' },
  { term: 'VEGETABLE', translation: 'Plant food' },
  { term: 'VEHICLE', translation: 'Transport means' },
  { term: 'VEIL', translation: 'Face covering' },
  { term: 'VEIN', translation: 'Blood vessel' },
  { term: 'VELOCITY', translation: 'Speed with direction' },
  { term: 'VELVET', translation: 'Soft fabric' },
  { term: 'VENDOR', translation: 'Seller' },
  { term: 'VENTURE', translation: 'Risky undertaking' },
  { term: 'VENUE', translation: 'Event location' },
  { term: 'VERB', translation: 'Action word' },
  { term: 'VERDICT', translation: 'Decision' },
  { term: 'VERIFY', translation: 'Confirm truth' },
  { term: 'VERSE', translation: 'Poetry line' },
  { term: 'VERSUS', translation: 'Against' },
  { term: 'VERTICAL', translation: 'Upright' },
  { term: 'VESSEL', translation: 'Container or ship' },
  { term: 'VETERAN', translation: 'Experienced person' },
  { term: 'VETO', translation: 'Reject or forbid' },
  { term: 'VIBRATE', translation: 'Shake rapidly' },
  { term: 'VICTIM', translation: 'Sufferer' },

  // Words with W
  { term: 'WITHDRAW', translation: 'Take back or remove' },
  { term: 'WORLDWIDE', translation: 'Global' },
  { term: 'WORSHIP', translation: 'Religious devotion' },
  { term: 'WORTHWHILE', translation: 'Worth the effort' },
  { term: 'WORTHY', translation: 'Deserving' },
  { term: 'WOUND', translation: 'Injury' },
  { term: 'WRAP', translation: 'Cover or enclose' },
  { term: 'WRECK', translation: 'Destroy or ruin' },
  { term: 'WRESTLE', translation: 'Grapple or fight' },
  { term: 'WRIST', translation: 'Hand joint' },
  { term: 'WRITE', translation: 'Put words on paper' },
  { term: 'WRONG', translation: 'Incorrect' },
  { term: 'WAGON', translation: 'Wheeled vehicle' },
  { term: 'WAIST', translation: 'Body middle' },
  { term: 'WAIT', translation: 'Stay until' },
  { term: 'WAKE', translation: 'Stop sleeping' },
  { term: 'WALK', translation: 'Move on foot' },
  { term: 'WALL', translation: 'Vertical structure' },
  { term: 'WANDER', translation: 'Roam aimlessly' },
  { term: 'WARM', translation: 'Moderately hot' },
  { term: 'WARN', translation: 'Alert of danger' },
  { term: 'WASH', translation: 'Clean with water' },
  { term: 'WASTE', translation: 'Use carelessly' },
  { term: 'WATCH', translation: 'Observe or timepiece' },
  { term: 'WAVE', translation: 'Water swell or gesture' },
  { term: 'WEAK', translation: 'Not strong' },
  { term: 'WEALTH', translation: 'Riches' },
  { term: 'WEAPON', translation: 'Fighting tool' },
  { term: 'WEAR', translation: 'Have on body' },
  { term: 'WEAVE', translation: 'Interlace threads' },
  { term: 'WEDDING', translation: 'Marriage ceremony' },
  { term: 'WEEK', translation: 'Seven days' },
  { term: 'WEIGH', translation: 'Measure heaviness' },
  { term: 'WEIGHT', translation: 'Heaviness' },
  { term: 'WEIRD', translation: 'Strange' },
  { term: 'WELCOME', translation: 'Greet warmly' },
  { term: 'WELFARE', translation: 'Well-being' },
  { term: 'WEST', translation: 'Direction' },
  { term: 'WHEAT', translation: 'Grain crop' },
  { term: 'WHEEL', translation: 'Circular object' },
  { term: 'WHEN', translation: 'At what time' },
  { term: 'WHERE', translation: 'In what place' },
  { term: 'WHICH', translation: 'What one' },
  { term: 'WHILE', translation: 'During the time' },
  { term: 'WHIP', translation: 'Lash or beat' },
  { term: 'WHISPER', translation: 'Speak softly' },
  { term: 'WHISTLE', translation: 'Shrill sound' },
  { term: 'WHITE', translation: 'Lightest color' },
  { term: 'WHOLE', translation: 'Complete' },
  { term: 'WHOM', translation: 'Objective case of who' },
  { term: 'WHOSE', translation: 'Possessive of who' },
  { term: 'WICKED', translation: 'Evil' },
  { term: 'WIDE', translation: 'Broad' },
  { term: 'WIDOW', translation: 'Surviving spouse' },
  { term: 'WIDTH', translation: 'Broadness' },
  { term: 'WILD', translation: 'Untamed' },
  { term: 'WILL', translation: 'Future tense or determination' },
  { term: 'WIN', translation: 'Achieve victory' },
  { term: 'WIND', translation: 'Moving air' },
  { term: 'WINDOW', translation: 'Glass opening' },
  { term: 'WINE', translation: 'Fermented drink' },
  { term: 'WING', translation: 'Flight limb' },
  { term: 'WINNER', translation: 'Victor' },
  { term: 'WINTER', translation: 'Cold season' },
  { term: 'WIRE', translation: 'Metal strand' },
  { term: 'WISDOM', translation: 'Deep knowledge' },
  { term: 'WISE', translation: 'Having wisdom' },
  { term: 'WISH', translation: 'Desire' },
  { term: 'WITCH', translation: 'Magical woman' },
  { term: 'WITNESS', translation: 'Observer' },
  { term: 'WIZARD', translation: 'Magical man' },
  { term: 'WOLF', translation: 'Wild canine' },
  { term: 'WOMAN', translation: 'Adult female' },
  { term: 'WONDER', translation: 'Marvel or question' },
  { term: 'WOOD', translation: 'Tree material' },
  { term: 'WOOL', translation: 'Sheep fiber' },
  { term: 'WORD', translation: 'Language unit' },
  { term: 'WORK', translation: 'Labor or function' },
  { term: 'WORKSHOP', translation: 'Training session' },
  { term: 'WORM', translation: 'Crawling creature' },
  { term: 'WORRY', translation: 'Feel anxious' },
]
