/**
 * @fileoverview Medium difficulty word bank for testing
 *
 * This dataset contains ~250 words with moderate crossing potential.
 * Characteristics:
 * - Balanced letter distribution
 * - Mix of common and less common letters
 * - Varied word lengths (4-10 letters)
 *
 * @module lib/test-utils/wordBanks/medium
 */

import type { TestWord } from '../types'

/**
 * Medium difficulty word bank
 * Balanced mix for realistic puzzle generation
 */
export const MEDIUM_WORDS: TestWord[] = [
  // Technology & Computing
  { term: 'COMPUTER', translation: 'Electronic device for processing data' },
  { term: 'KEYBOARD', translation: 'Input device with keys' },
  { term: 'MONITOR', translation: 'Display screen' },
  { term: 'PRINTER', translation: 'Device that produces paper output' },
  { term: 'SOFTWARE', translation: 'Computer programs' },
  { term: 'HARDWARE', translation: 'Physical computer parts' },
  { term: 'INTERNET', translation: 'Global network' },
  { term: 'WEBSITE', translation: 'Online page' },
  { term: 'DATABASE', translation: 'Organized data collection' },
  { term: 'NETWORK', translation: 'Connected computers' },
  { term: 'DIGITAL', translation: 'Using binary data' },
  { term: 'MOBILE', translation: 'Portable device' },
  { term: 'LAPTOP', translation: 'Portable computer' },
  { term: 'TABLET', translation: 'Touchscreen device' },
  { term: 'ROUTER', translation: 'Network device' },
  { term: 'SERVER', translation: 'Host computer' },
  { term: 'BACKUP', translation: 'Data copy' },
  { term: 'UPDATE', translation: 'Software improvement' },
  { term: 'UPLOAD', translation: 'Send data' },
  { term: 'DOWNLOAD', translation: 'Receive data' },
  { term: 'PASSWORD', translation: 'Security code' },
  { term: 'USERNAME', translation: 'Account identifier' },
  { term: 'BROWSER', translation: 'Web navigation tool' },
  { term: 'SEARCH', translation: 'Look for information' },
  { term: 'ENGINE', translation: 'Machine or search tool' },
  { term: 'PLATFORM', translation: 'Computing base' },
  { term: 'PROGRAM', translation: 'Software application' },
  { term: 'CODING', translation: 'Writing code' },
  { term: 'DEBUG', translation: 'Fix errors' },
  { term: 'COMPILE', translation: 'Convert code' },

  // Science & Nature
  { term: 'SCIENCE', translation: 'Systematic knowledge' },
  { term: 'BIOLOGY', translation: 'Study of life' },
  { term: 'PHYSICS', translation: 'Study of matter' },
  { term: 'CHEMISTRY', translation: 'Study of substances' },
  { term: 'ECOLOGY', translation: 'Study of ecosystems' },
  { term: 'GEOLOGY', translation: 'Study of Earth' },
  { term: 'WEATHER', translation: 'Atmospheric conditions' },
  { term: 'CLIMATE', translation: 'Long-term weather' },
  { term: 'ENERGY', translation: 'Capacity to do work' },
  { term: 'MATTER', translation: 'Physical substance' },
  { term: 'ELEMENT', translation: 'Basic substance' },
  { term: 'COMPOUND', translation: 'Combined elements' },
  { term: 'MOLECULE', translation: 'Group of atoms' },
  { term: 'ELECTRON', translation: 'Subatomic particle' },
  { term: 'PROTON', translation: 'Positive particle' },
  { term: 'NEUTRON', translation: 'Neutral particle' },
  { term: 'GRAVITY', translation: 'Force of attraction' },
  { term: 'MOTION', translation: 'Movement' },
  { term: 'VELOCITY', translation: 'Speed with direction' },
  { term: 'PRESSURE', translation: 'Force per area' },
  { term: 'TEMPERATURE', translation: 'Heat measure' },
  { term: 'VOLCANO', translation: 'Erupting mountain' },
  { term: 'EARTHQUAKE', translation: 'Ground shaking' },
  { term: 'TSUNAMI', translation: 'Large ocean wave' },
  { term: 'HURRICANE', translation: 'Tropical storm' },
  { term: 'TORNADO', translation: 'Violent wind' },
  { term: 'LIGHTNING', translation: 'Electric discharge' },
  { term: 'THUNDER', translation: 'Sound of lightning' },
  { term: 'RAINBOW', translation: 'Colored arc' },
  { term: 'SOLAR', translation: 'Related to sun' },
  { term: 'LUNAR', translation: 'Related to moon' },
  { term: 'PLANET', translation: 'Celestial body' },
  { term: 'GALAXY', translation: 'Star system' },
  { term: 'COMET', translation: 'Icy celestial object' },
  { term: 'METEOR', translation: 'Falling space rock' },
  { term: 'ASTEROID', translation: 'Small rocky body' },
  { term: 'SATELLITE', translation: 'Orbiting object' },
  { term: 'TELESCOPE', translation: 'Viewing instrument' },
  { term: 'MICROSCOPE', translation: 'Magnifying tool' },
  { term: 'LABORATORY', translation: 'Research facility' },

  // Animals & Plants
  { term: 'ELEPHANT', translation: 'Large mammal with trunk' },
  { term: 'GIRAFFE', translation: 'Long-necked animal' },
  { term: 'DOLPHIN', translation: 'Intelligent sea mammal' },
  { term: 'PENGUIN', translation: 'Flightless bird' },
  { term: 'BUTTERFLY', translation: 'Winged insect' },
  { term: 'MOSQUITO', translation: 'Biting insect' },
  { term: 'CROCODILE', translation: 'Large reptile' },
  { term: 'KANGAROO', translation: 'Hopping marsupial' },
  { term: 'LEOPARD', translation: 'Spotted cat' },
  { term: 'CHEETAH', translation: 'Fast cat' },
  { term: 'GORILLA', translation: 'Large ape' },
  { term: 'MONKEY', translation: 'Primate' },
  { term: 'ZEBRA', translation: 'Striped horse' },
  { term: 'TIGER', translation: 'Striped big cat' },
  { term: 'LION', translation: 'King of animals' },
  { term: 'BEAR', translation: 'Large carnivore' },
  { term: 'WOLF', translation: 'Wild canine' },
  { term: 'FOX', translation: 'Cunning animal' },
  { term: 'DEER', translation: 'Antlered animal' },
  { term: 'RABBIT', translation: 'Hopping mammal' },
  { term: 'SQUIRREL', translation: 'Tree-climbing rodent' },
  { term: 'EAGLE', translation: 'Bird of prey' },
  { term: 'FALCON', translation: 'Hunting bird' },
  { term: 'PARROT', translation: 'Colorful talking bird' },
  { term: 'PIGEON', translation: 'Common city bird' },
  { term: 'SPARROW', translation: 'Small brown bird' },
  { term: 'ROBIN', translation: 'Red-breasted bird' },
  { term: 'SHARK', translation: 'Predatory fish' },
  { term: 'WHALE', translation: 'Largest mammal' },
  { term: 'OCTOPUS', translation: 'Eight-armed creature' },
  { term: 'JELLYFISH', translation: 'Transparent sea creature' },
  { term: 'STARFISH', translation: 'Star-shaped sea animal' },
  { term: 'CORAL', translation: 'Marine organism' },
  { term: 'SEAWEED', translation: 'Marine plant' },
  { term: 'FLOWER', translation: 'Blooming plant part' },
  { term: 'TREE', translation: 'Woody plant' },
  { term: 'LEAF', translation: 'Plant blade' },
  { term: 'ROOT', translation: 'Underground plant part' },
  { term: 'STEM', translation: 'Plant stalk' },
  { term: 'BRANCH', translation: 'Tree limb' },
  { term: 'SEED', translation: 'Plant embryo' },
  { term: 'FRUIT', translation: 'Plant product' },
  { term: 'BERRY', translation: 'Small fruit' },
  { term: 'GRASS', translation: 'Ground cover' },
  { term: 'MOSS', translation: 'Small green plant' },
  { term: 'FERN', translation: 'Leafy plant' },
  { term: 'CACTUS', translation: 'Desert plant' },
  { term: 'BAMBOO', translation: 'Tall grass' },

  // Geography & Places
  { term: 'CONTINENT', translation: 'Large landmass' },
  { term: 'COUNTRY', translation: 'Nation state' },
  { term: 'CAPITAL', translation: 'Main city' },
  { term: 'PROVINCE', translation: 'State or region' },
  { term: 'DISTRICT', translation: 'Administrative area' },
  { term: 'VILLAGE', translation: 'Small settlement' },
  { term: 'TOWN', translation: 'Urban area' },
  { term: 'CITY', translation: 'Large urban area' },
  { term: 'SUBURB', translation: 'Residential area' },
  { term: 'DOWNTOWN', translation: 'City center' },
  { term: 'HIGHWAY', translation: 'Main road' },
  { term: 'BRIDGE', translation: 'Crossing structure' },
  { term: 'TUNNEL', translation: 'Underground passage' },
  { term: 'HARBOR', translation: 'Port area' },
  { term: 'AIRPORT', translation: 'Flight terminal' },
  { term: 'STATION', translation: 'Transport stop' },
  { term: 'MUSEUM', translation: 'Art/history building' },
  { term: 'LIBRARY', translation: 'Book collection' },
  { term: 'THEATER', translation: 'Performance venue' },
  { term: 'STADIUM', translation: 'Sports arena' },
  { term: 'PALACE', translation: 'Royal residence' },
  { term: 'CASTLE', translation: 'Fortified building' },
  { term: 'TEMPLE', translation: 'Religious building' },
  { term: 'CHURCH', translation: 'Christian place' },
  { term: 'MOSQUE', translation: 'Islamic place' },
  { term: 'SHRINE', translation: 'Sacred place' },
  { term: 'MONUMENT', translation: 'Memorial structure' },
  { term: 'STATUE', translation: 'Carved figure' },
  { term: 'TOWER', translation: 'Tall structure' },
  { term: 'PYRAMID', translation: 'Ancient structure' },

  // Food & Cooking
  { term: 'KITCHEN', translation: 'Cooking room' },
  { term: 'RECIPE', translation: 'Cooking instructions' },
  { term: 'INGREDIENT', translation: 'Food component' },
  { term: 'FLAVOR', translation: 'Taste quality' },
  { term: 'SEASON', translation: 'Add spices' },
  { term: 'BOIL', translation: 'Heat in water' },
  { term: 'FRY', translation: 'Cook in oil' },
  { term: 'BAKE', translation: 'Cook in oven' },
  { term: 'GRILL', translation: 'Cook on grate' },
  { term: 'ROAST', translation: 'Cook with dry heat' },
  { term: 'STEAM', translation: 'Cook with vapor' },
  { term: 'SLICE', translation: 'Cut thinly' },
  { term: 'CHOP', translation: 'Cut into pieces' },
  { term: 'BLEND', translation: 'Mix together' },
  { term: 'STIR', translation: 'Mix with motion' },
  { term: 'POUR', translation: 'Transfer liquid' },
  { term: 'SERVE', translation: 'Present food' },
  { term: 'MEAL', translation: 'Food occasion' },
  { term: 'BREAKFAST', translation: 'Morning meal' },
  { term: 'LUNCH', translation: 'Midday meal' },
  { term: 'DINNER', translation: 'Evening meal' },
  { term: 'SNACK', translation: 'Small meal' },
  { term: 'DESSERT', translation: 'Sweet course' },
  { term: 'BEVERAGE', translation: 'Drink' },
  { term: 'COFFEE', translation: 'Hot drink' },
  { term: 'TEA', translation: 'Brewed drink' },
  { term: 'JUICE', translation: 'Fruit liquid' },
  { term: 'SOUP', translation: 'Liquid dish' },
  { term: 'SALAD', translation: 'Mixed vegetables' },
  { term: 'SANDWICH', translation: 'Bread with filling' },
  { term: 'PIZZA', translation: 'Italian flatbread' },
  { term: 'PASTA', translation: 'Italian noodles' },
  { term: 'RICE', translation: 'Grain staple' },
  { term: 'BREAD', translation: 'Baked staple' },
  { term: 'CHEESE', translation: 'Dairy product' },
  { term: 'BUTTER', translation: 'Milk fat' },
  { term: 'CREAM', translation: 'Thick milk' },
  { term: 'YOGURT', translation: 'Fermented milk' },
  { term: 'MEAT', translation: 'Animal flesh' },
  { term: 'CHICKEN', translation: 'Poultry' },
  { term: 'BEEF', translation: 'Cow meat' },
  { term: 'PORK', translation: 'Pig meat' },
  { term: 'FISH', translation: 'Aquatic animal' },
  { term: 'SHRIMP', translation: 'Small crustacean' },
  { term: 'VEGETABLE', translation: 'Plant food' },
  { term: 'CARROT', translation: 'Orange root' },
  { term: 'POTATO', translation: 'Starchy tuber' },
  { term: 'TOMATO', translation: 'Red fruit/vegetable' },
  { term: 'ONION', translation: 'Layered bulb' },
  { term: 'GARLIC', translation: 'Pungent bulb' },
  { term: 'PEPPER', translation: 'Spice or vegetable' },
  { term: 'MUSHROOM', translation: 'Edible fungus' },

  // Arts & Culture
  { term: 'MUSIC', translation: 'Organized sound' },
  { term: 'PAINTING', translation: 'Visual art' },
  { term: 'SCULPTURE', translation: 'Three-dimensional art' },
  { term: 'DRAWING', translation: 'Sketched art' },
  { term: 'POETRY', translation: 'Verse writing' },
  { term: 'NOVEL', translation: 'Long fiction' },
  { term: 'STORY', translation: 'Narrative' },
  { term: 'DRAMA', translation: 'Stage play' },
  { term: 'COMEDY', translation: 'Humorous work' },
  { term: 'TRAGEDY', translation: 'Sad play' },
  { term: 'OPERA', translation: 'Musical drama' },
  { term: 'BALLET', translation: 'Dance art' },
  { term: 'CONCERT', translation: 'Musical performance' },
  { term: 'SYMPHONY', translation: 'Orchestral work' },
  { term: 'MELODY', translation: 'Musical tune' },
  { term: 'RHYTHM', translation: 'Beat pattern' },
  { term: 'HARMONY', translation: 'Musical agreement' },
  { term: 'INSTRUMENT', translation: 'Music tool' },
  { term: 'PIANO', translation: 'Keyboard instrument' },
  { term: 'GUITAR', translation: 'String instrument' },
  { term: 'VIOLIN', translation: 'Bowed string' },
  { term: 'DRUM', translation: 'Percussion instrument' },
  { term: 'TRUMPET', translation: 'Brass instrument' },
  { term: 'FLUTE', translation: 'Wind instrument' },
  { term: 'CULTURE', translation: 'Social customs' },
  { term: 'TRADITION', translation: 'Passed custom' },
  { term: 'FESTIVAL', translation: 'Celebration event' },
  { term: 'CEREMONY', translation: 'Formal ritual' },
  { term: 'CELEBRATION', translation: 'Joyful event' },
  { term: 'HOLIDAY', translation: 'Special day' },

  // Sports & Activities
  { term: 'SPORT', translation: 'Physical activity' },
  { term: 'FOOTBALL', translation: 'Ball game' },
  { term: 'BASKETBALL', translation: 'Hoop game' },
  { term: 'BASEBALL', translation: 'Bat game' },
  { term: 'TENNIS', translation: 'Racket game' },
  { term: 'GOLF', translation: 'Club game' },
  { term: 'HOCKEY', translation: 'Stick game' },
  { term: 'SWIMMING', translation: 'Water sport' },
  { term: 'RUNNING', translation: 'Fast movement' },
  { term: 'CYCLING', translation: 'Bike riding' },
  { term: 'SKIING', translation: 'Snow sport' },
  { term: 'SKATING', translation: 'Gliding sport' },
  { term: 'CLIMBING', translation: 'Ascending sport' },
  { term: 'HIKING', translation: 'Trail walking' },
  { term: 'CAMPING', translation: 'Outdoor staying' },
  { term: 'FISHING', translation: 'Catching fish' },
  { term: 'HUNTING', translation: 'Pursuing game' },
  { term: 'EXERCISE', translation: 'Physical training' },
  { term: 'TRAINING', translation: 'Practice sessions' },
  { term: 'COMPETITION', translation: 'Contest' },
  { term: 'CHAMPION', translation: 'Winner' },
  { term: 'VICTORY', translation: 'Win' },
  { term: 'DEFEAT', translation: 'Loss' },
  { term: 'SCORE', translation: 'Points earned' },
  { term: 'GOAL', translation: 'Target or point' },
  { term: 'TEAM', translation: 'Group of players' },
  { term: 'COACH', translation: 'Trainer' },
  { term: 'ATHLETE', translation: 'Sports person' },
  { term: 'PLAYER', translation: 'Participant' },
  { term: 'REFEREE', translation: 'Game official' },
]
